.TH "/home/james/NetBeansProjects/ride/src Directory Reference" 3 "Tue Jun 2 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBuild\&.cpp\fP"
.br
.ti -1c
.RI "file \fBBuild\&.h\fP"
.br
.ti -1c
.RI "file \fBCentralGui\&.cpp\fP"
.br
.ti -1c
.RI "file \fBCentralGui\&.h\fP"
.br
.ti -1c
.RI "file \fBDirectory\&.cpp\fP"
.br
.ti -1c
.RI "file \fBDirectory\&.h\fP"
.br
.ti -1c
.RI "file \fBEnvCmds\&.cpp\fP"
.br
.ti -1c
.RI "file \fBEnvCmds\&.h\fP"
.br
.ti -1c
.RI "file \fBFileGui\&.cpp\fP"
.br
.ti -1c
.RI "file \fBFileGui\&.h\fP"
.br
.ti -1c
.RI "file \fBFileTreeGui\&.cpp\fP"
.br
.ti -1c
.RI "file \fBFileTreeGui\&.h\fP"
.br
.ti -1c
.RI "file \fBHighlighter\&.cpp\fP"
.br
.ti -1c
.RI "file \fBHighlighter\&.h\fP"
.br
.ti -1c
.RI "file \fBLineNumberArea\&.cpp\fP"
.br
.ti -1c
.RI "file \fBLineNumberArea\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMasterActions\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMasterActions\&.h\fP"
.br
.ti -1c
.RI "file \fBMasterGui\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMasterGui\&.h\fP"
.br
.ti -1c
.RI "file \fBMasterMenus\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMasterMenus\&.h\fP"
.br
.ti -1c
.RI "file \fBMasterStatusBar\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMasterStatusBar\&.h\fP"
.br
.ti -1c
.RI "file \fBMasterToolBars\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMasterToolBars\&.h\fP"
.br
.ti -1c
.RI "file \fBModifyCMakeLists\&.cpp\fP"
.br
.ti -1c
.RI "file \fBModifyCMakeLists\&.h\fP"
.br
.ti -1c
.RI "file \fBModifyManifest\&.cpp\fP"
.br
.ti -1c
.RI "file \fBModifyManifest\&.h\fP"
.br
.ti -1c
.RI "file \fBNavigatorGui\&.cpp\fP"
.br
.ti -1c
.RI "file \fBNavigatorGui\&.h\fP"
.br
.ti -1c
.RI "file \fBNewFileGui\&.cpp\fP"
.br
.ti -1c
.RI "file \fBNewFileGui\&.h\fP"
.br
.ti -1c
.RI "file \fBNewFilePage_1\&.cpp\fP"
.br
.ti -1c
.RI "file \fBNewFilePage_1\&.h\fP"
.br
.ti -1c
.RI "file \fBNewFilePage_2\&.cpp\fP"
.br
.ti -1c
.RI "file \fBNewFilePage_2\&.h\fP"
.br
.ti -1c
.RI "file \fBNewFilePage_3\&.cpp\fP"
.br
.ti -1c
.RI "file \fBNewFilePage_3\&.h\fP"
.br
.ti -1c
.RI "file \fBNewFilePage_4\&.cpp\fP"
.br
.ti -1c
.RI "file \fBNewFilePage_4\&.h\fP"
.br
.ti -1c
.RI "file \fBNewProjectGui\&.cpp\fP"
.br
.ti -1c
.RI "file \fBNewProjectGui\&.h\fP"
.br
.ti -1c
.RI "file \fBNewProjectPage_1\&.cpp\fP"
.br
.ti -1c
.RI "file \fBNewProjectPage_1\&.h\fP"
.br
.ti -1c
.RI "file \fBNewProjectPage_2\&.cpp\fP"
.br
.ti -1c
.RI "file \fBNewProjectPage_2\&.h\fP"
.br
.ti -1c
.RI "file \fBNewProjectPage_3\&.cpp\fP"
.br
.ti -1c
.RI "file \fBNewProjectPage_3\&.h\fP"
.br
.ti -1c
.RI "file \fBNewProjectPage_4\&.cpp\fP"
.br
.ti -1c
.RI "file \fBNewProjectPage_4\&.h\fP"
.br
.ti -1c
.RI "file \fBOpeningGui\&.cpp\fP"
.br
.ti -1c
.RI "file \fBOpeningGui\&.h\fP"
.br
.ti -1c
.RI "file \fBOpenProjectGui\&.cpp\fP"
.br
.ti -1c
.RI "file \fBOpenProjectGui\&.h\fP"
.br
.ti -1c
.RI "file \fBOutputGui\&.cpp\fP"
.br
.ti -1c
.RI "file \fBOutputGui\&.h\fP"
.br
.ti -1c
.RI "file \fBParseFontConfigXml\&.cpp\fP"
.br
.ti -1c
.RI "file \fBParseFontConfigXml\&.h\fP"
.br
.ti -1c
.RI "file \fBPhysicalAttribLog\&.cpp\fP"
.br
.ti -1c
.RI "file \fBPhysicalAttribLog\&.h\fP"
.br
.ti -1c
.RI "file \fBRideFile\&.cpp\fP"
.br
.ti -1c
.RI "file \fBRideFile\&.h\fP"
.br
.ti -1c
.RI "file \fBRideFont\&.cpp\fP"
.br
.ti -1c
.RI "file \fBRideFont\&.h\fP"
.br
.ti -1c
.RI "file \fBRunGui\&.cpp\fP"
.br
.ti -1c
.RI "file \fBRunGui\&.h\fP"
.br
.ti -1c
.RI "file \fBRunPage_1\&.cpp\fP"
.br
.ti -1c
.RI "file \fBRunPage_1\&.h\fP"
.br
.ti -1c
.RI "file \fBRunPage_2\&.cpp\fP"
.br
.ti -1c
.RI "file \fBRunPage_2\&.h\fP"
.br
.ti -1c
.RI "file \fBRunPage_3\&.cpp\fP"
.br
.ti -1c
.RI "file \fBRunPage_3\&.h\fP"
.br
.ti -1c
.RI "file \fBSaveAll\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSaveAll\&.h\fP"
.br
.ti -1c
.RI "file \fBScoutGui\&.cpp\fP"
.br
.ti -1c
.RI "file \fBScoutGui\&.h\fP"
.br
.ti -1c
.RI "file \fBSplashScreen\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSplashScreen\&.h\fP"
.br
.ti -1c
.RI "file \fBTabGui\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTabGui\&.h\fP"
.br
.ti -1c
.RI "file \fBTerminal\&.cpp\fP"
.br
.ti -1c
.RI "file \fBTerminal\&.h\fP"
.br
.ti -1c
.RI "file \fBUnixConsoleText\&.cpp\fP"
.br
.ti -1c
.RI "file \fBUnixConsoleText\&.h\fP"
.br
.ti -1c
.RI "file \fBWindowsConsoleText\&.cpp\fP"
.br
.ti -1c
.RI "file \fBWindowsConsoleText\&.h\fP"
.br
.ti -1c
.RI "file \fBXmlMaster\&.cpp\fP"
.br
.ti -1c
.RI "file \fBXmlMaster\&.h\fP"
.br
.in -1c
