.TH "Build" 3 "Sat Jun 6 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Build \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Build\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBuild\fP ()"
.br
.ti -1c
.RI "void \fBrunBuildCmd\fP ()"
.br
.ti -1c
.RI "\fB~Build\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "const QString * \fBPKG_OPTION_STR_PTR\fP"
.br
.ti -1c
.RI "QStringList * \fBpkgStrLstPtr\fP"
.br
.ti -1c
.RI "QProcess * \fBbuildProcessPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file Build\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Build::Build ()"

.PP
Definition at line 4 of file Build\&.cpp\&.
.SS "Build::~Build ()"

.PP
Definition at line 19 of file Build\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Build::runBuildCmd ()"

.PP
Definition at line 12 of file Build\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QProcess* Build::buildProcessPtr\fC [private]\fP"

.PP
Definition at line 32 of file Build\&.h\&.
.SS "const QString* Build::PKG_OPTION_STR_PTR\fC [private]\fP"

.PP
Definition at line 30 of file Build\&.h\&.
.SS "QStringList* Build::pkgStrLstPtr\fC [private]\fP"

.PP
Definition at line 31 of file Build\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
