.TH "/home/james/NetBeansProjects/ride/src/Build.h" 3 "Tue Jun 2 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/Build.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QDebug>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QStringList>\fP
.br
\fC#include <QProcess>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBuild\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
