.TH "CentralGui" 3 "Fri Jun 12 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CentralGui \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CentralGui\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCentralGui\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetNorthGuiPtr\fP (\fBTabGui\fP *\fBnorthGuiPtr\fP)"
.br
.ti -1c
.RI "\fBTabGui\fP * \fBgetNorthGuiPtr\fP ()"
.br
.ti -1c
.RI "void \fBsetFileTreeGuiPtr\fP (\fBFileTreeGui\fP *\fBfileTreeGuiPtr\fP)"
.br
.ti -1c
.RI "\fBFileTreeGui\fP * \fBgetFileTreeGuiPtr\fP ()"
.br
.ti -1c
.RI "void \fBsetNavigatorGuiPtr\fP (\fBNavigatorGui\fP *\fBnavigatorGuiPtr\fP)"
.br
.ti -1c
.RI "\fBNavigatorGui\fP * \fBgetNavigatorGuiPtr\fP ()"
.br
.ti -1c
.RI "void \fBsetSouthGuiPtr\fP (\fBOutputGui\fP *\fBsouthGuiPtr\fP)"
.br
.ti -1c
.RI "\fBOutputGui\fP * \fBgetSouthGuiPtr\fP ()"
.br
.ti -1c
.RI "void \fBpassNorthTabWidgetPtr\fP (QTabWidget *northTabWidgetPtr)"
.br
.ti -1c
.RI "void \fBpassSouthTabWidgetPtr\fP (QTabWidget *southTabWidgetPtr)"
.br
.ti -1c
.RI "\fB~CentralGui\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBTabGui\fP * \fBnorthGuiPtr\fP"
.br
.ti -1c
.RI "\fBFileTreeGui\fP * \fBfileTreeGuiPtr\fP"
.br
.ti -1c
.RI "\fBNavigatorGui\fP * \fBnavigatorGuiPtr\fP"
.br
.ti -1c
.RI "\fBOutputGui\fP * \fBsouthGuiPtr\fP"
.br
.ti -1c
.RI "QGridLayout * \fBouterLayout\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file CentralGui\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CentralGui::CentralGui (QWidget *parent = \fC0\fP)"

.PP
Definition at line 4 of file CentralGui\&.cpp\&.
.SS "CentralGui::~CentralGui ()"

.PP
Definition at line 89 of file CentralGui\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBFileTreeGui\fP * CentralGui::getFileTreeGuiPtr ()"

.PP
Definition at line 47 of file CentralGui\&.cpp\&.
.SS "\fBNavigatorGui\fP * CentralGui::getNavigatorGuiPtr ()"

.PP
Definition at line 59 of file CentralGui\&.cpp\&.
.SS "\fBTabGui\fP * CentralGui::getNorthGuiPtr ()"

.PP
Definition at line 35 of file CentralGui\&.cpp\&.
.SS "\fBOutputGui\fP * CentralGui::getSouthGuiPtr ()"

.PP
Definition at line 71 of file CentralGui\&.cpp\&.
.SS "void CentralGui::passNorthTabWidgetPtr (QTabWidget *northTabWidgetPtr)"

.PP
Definition at line 77 of file CentralGui\&.cpp\&.
.SS "void CentralGui::passSouthTabWidgetPtr (QTabWidget *southTabWidgetPtr)"

.PP
Definition at line 83 of file CentralGui\&.cpp\&.
.SS "void CentralGui::setFileTreeGuiPtr (\fBFileTreeGui\fP *fileTreeGuiPtr)"

.PP
Definition at line 41 of file CentralGui\&.cpp\&.
.SS "void CentralGui::setNavigatorGuiPtr (\fBNavigatorGui\fP *navigatorGuiPtr)"

.PP
Definition at line 53 of file CentralGui\&.cpp\&.
.SS "void CentralGui::setNorthGuiPtr (\fBTabGui\fP *northGuiPtr)"

.PP
Definition at line 29 of file CentralGui\&.cpp\&.
.SS "void CentralGui::setSouthGuiPtr (\fBOutputGui\fP *southGuiPtr)"

.PP
Definition at line 65 of file CentralGui\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFileTreeGui\fP* CentralGui::fileTreeGuiPtr\fC [private]\fP"

.PP
Definition at line 33 of file CentralGui\&.h\&.
.SS "\fBNavigatorGui\fP* CentralGui::navigatorGuiPtr\fC [private]\fP"

.PP
Definition at line 34 of file CentralGui\&.h\&.
.SS "\fBTabGui\fP* CentralGui::northGuiPtr\fC [private]\fP"

.PP
Definition at line 32 of file CentralGui\&.h\&.
.SS "QGridLayout* CentralGui::outerLayout\fC [private]\fP"

.PP
Definition at line 37 of file CentralGui\&.h\&.
.SS "\fBOutputGui\fP* CentralGui::southGuiPtr\fC [private]\fP"

.PP
Definition at line 35 of file CentralGui\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
