.TH "Directory" 3 "Tue Jun 2 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Directory \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Directory\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDirectory\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetDirPtr\fP (QDir *\fBdirPtr\fP)"
.br
.ti -1c
.RI "QDir * \fBgetDirPtr\fP ()"
.br
.ti -1c
.RI "void \fBsetDirTypePtr\fP (\fBDirType\fP *\fBdirTypePtr\fP)"
.br
.ti -1c
.RI "\fBDirType\fP * \fBgetDirTypePtr\fP ()"
.br
.ti -1c
.RI "void \fBpushBackToChildDirsPtrVec\fP (QDir *dir)"
.br
.ti -1c
.RI "QVector< QDir * > \fBgetChildDirsPtrVec\fP ()"
.br
.ti -1c
.RI "void \fBpushBackToChildFilesPtrVec\fP (QFile *file)"
.br
.ti -1c
.RI "QVector< QFile * > \fBgetChildFilesPtrVec\fP ()"
.br
.ti -1c
.RI "QString * \fBtoString\fP ()"
.br
.ti -1c
.RI "\fB~Directory\fP ()"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "enum \fBDirType\fP { \fBNODE\fP, \fBSRC\fP, \fBINCLUDE\fP, \fBBUILD\fP, \fBDEVEL\fP, \fBOTHER\fP }"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QDir * \fBdirPtr\fP"
.br
.ti -1c
.RI "\fBDirType\fP * \fBdirTypePtr\fP"
.br
.ti -1c
.RI "QVector< QDir * > \fBchildDirsPtrVec\fP"
.br
.ti -1c
.RI "QVector< QFile * > \fBchildFilesPtrVec\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file Directory\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBDirectory::DirType\fP\fC [private]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINODE \fP\fP
.TP
\fB\fISRC \fP\fP
.TP
\fB\fIINCLUDE \fP\fP
.TP
\fB\fIBUILD \fP\fP
.TP
\fB\fIDEVEL \fP\fP
.TP
\fB\fIOTHER \fP\fP
.PP
Definition at line 30 of file Directory\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Directory::Directory (QWidget *parent = \fC0\fP)"

.PP
Definition at line 4 of file Directory\&.cpp\&.
.SS "Directory::~Directory ()"

.PP
Definition at line 86 of file Directory\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QVector< QDir * > Directory::getChildDirsPtrVec ()"

.PP
Definition at line 40 of file Directory\&.cpp\&.
.SS "QVector< QFile * > Directory::getChildFilesPtrVec ()"

.PP
Definition at line 52 of file Directory\&.cpp\&.
.SS "QDir * Directory::getDirPtr ()"

.PP
Definition at line 16 of file Directory\&.cpp\&.
.SS "\fBDirectory::DirType\fP * Directory::getDirTypePtr ()"

.PP
Definition at line 28 of file Directory\&.cpp\&.
.SS "void Directory::pushBackToChildDirsPtrVec (QDir *dir)"

.PP
Definition at line 34 of file Directory\&.cpp\&.
.SS "void Directory::pushBackToChildFilesPtrVec (QFile *file)"

.PP
Definition at line 46 of file Directory\&.cpp\&.
.SS "void Directory::setDirPtr (QDir *dirPtr)"

.PP
Definition at line 10 of file Directory\&.cpp\&.
.SS "void Directory::setDirTypePtr (\fBDirectory::DirType\fP *dirTypePtr)"

.PP
Definition at line 22 of file Directory\&.cpp\&.
.SS "QString * Directory::toString ()"

.PP
Definition at line 58 of file Directory\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QVector<QDir*> Directory::childDirsPtrVec\fC [private]\fP"

.PP
Definition at line 42 of file Directory\&.h\&.
.SS "QVector<QFile*> Directory::childFilesPtrVec\fC [private]\fP"

.PP
Definition at line 43 of file Directory\&.h\&.
.SS "QDir* Directory::dirPtr\fC [private]\fP"

.PP
Definition at line 40 of file Directory\&.h\&.
.SS "\fBDirType\fP* Directory::dirTypePtr\fC [private]\fP"

.PP
Definition at line 41 of file Directory\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
