.TH "FileTreeGui" 3 "Tue Jun 2 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileTreeGui \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FileTreeGui\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileTreeGui\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetMasterTabWidgetPtr\fP (QTabWidget *\fBmasterTabWidgetPtr\fP)"
.br
.ti -1c
.RI "QTabWidget * \fBgetMasterTabWidgetPtr\fP ()"
.br
.ti -1c
.RI "\fB~FileTreeGui\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsetProjectRootAbsPathStrPtr\fP (QString *\fBprojectRootAbsPathStrPtr\fP)"
.br
.ti -1c
.RI "static QString * \fBgetProjectRootAbsPathStrPtr\fP ()"
.br
.ti -1c
.RI "static void \fBrefresh\fP ()"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBhandleRightClickSlot\fP (const QPoint &)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QGridLayout * \fBouterLayout\fP"
.br
.ti -1c
.RI "QTabWidget * \fBmasterTabWidgetPtr\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static QTreeView * \fBtree\fP"
.br
.ti -1c
.RI "static QListView * \fBlist\fP"
.br
.ti -1c
.RI "static QSplitter * \fBsplitter\fP"
.br
.ti -1c
.RI "static QFileSystemModel * \fBmodel\fP"
.br
.ti -1c
.RI "static QString * \fBprojectRootAbsPathStrPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 29 of file FileTreeGui\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FileTreeGui::FileTreeGui (QWidget *parent = \fC0\fP)"

.PP
Definition at line 11 of file FileTreeGui\&.cpp\&.
.SS "FileTreeGui::~FileTreeGui ()"

.PP
Definition at line 116 of file FileTreeGui\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QTabWidget * FileTreeGui::getMasterTabWidgetPtr ()"

.PP
Definition at line 110 of file FileTreeGui\&.cpp\&.
.SS "QString * FileTreeGui::getProjectRootAbsPathStrPtr ()\fC [static]\fP"

.PP
Definition at line 78 of file FileTreeGui\&.cpp\&.
.SS "void FileTreeGui::handleRightClickSlot (const QPoint &pos)\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 48 of file FileTreeGui\&.cpp\&.
.SS "void FileTreeGui::refresh ()\fC [static]\fP"

.PP
Definition at line 84 of file FileTreeGui\&.cpp\&.
.SS "void FileTreeGui::setMasterTabWidgetPtr (QTabWidget *masterTabWidgetPtr)"

.PP
Definition at line 104 of file FileTreeGui\&.cpp\&.
.SS "void FileTreeGui::setProjectRootAbsPathStrPtr (QString *projectRootAbsPathStrPtr)\fC [static]\fP"

.PP
Definition at line 72 of file FileTreeGui\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QListView * FileTreeGui::list\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 35 of file FileTreeGui\&.h\&.
.SS "QTabWidget* FileTreeGui::masterTabWidgetPtr\fC [private]\fP"

.PP
Definition at line 42 of file FileTreeGui\&.h\&.
.SS "QFileSystemModel * FileTreeGui::model\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 37 of file FileTreeGui\&.h\&.
.SS "QGridLayout* FileTreeGui::outerLayout\fC [private]\fP"

.PP
Definition at line 39 of file FileTreeGui\&.h\&.
.SS "QString * FileTreeGui::projectRootAbsPathStrPtr\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 41 of file FileTreeGui\&.h\&.
.SS "QSplitter * FileTreeGui::splitter\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 36 of file FileTreeGui\&.h\&.
.SS "QTreeView * FileTreeGui::tree\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 34 of file FileTreeGui\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
