.TH "FileTreeGui" 3 "Sat Jun 6 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileTreeGui \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FileTreeGui\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileTreeGui\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetMasterTabWidgetPtr\fP (QTabWidget *\fBmasterTabWidgetPtr\fP)"
.br
.ti -1c
.RI "QTabWidget * \fBgetMasterTabWidgetPtr\fP ()"
.br
.ti -1c
.RI "\fB~FileTreeGui\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBinitTree\fP ()"
.br
.ti -1c
.RI "static void \fBaddChildren\fP (QTreeWidgetItem *item, QString filePath)"
.br
.ti -1c
.RI "static void \fBsetProjectRootAbsPathStrPtr\fP (QString *\fBprojectRootAbsPathStrPtr\fP)"
.br
.ti -1c
.RI "static QString * \fBgetProjectRootAbsPathStrPtr\fP ()"
.br
.ti -1c
.RI "static void \fBrefresh\fP ()"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBhandleShowDirectorySlot\fP (QTreeWidgetItem *item, int)"
.br
.ti -1c
.RI "void \fBhandleRightClickSlot\fP (const QPoint &)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QGridLayout * \fBouterLayout\fP"
.br
.ti -1c
.RI "QTabWidget * \fBmasterTabWidgetPtr\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static QTreeWidget * \fBtrueTree\fP"
.br
.ti -1c
.RI "static QSplitter * \fBsplitter\fP"
.br
.ti -1c
.RI "static QString * \fBprojectRootAbsPathStrPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file FileTreeGui\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FileTreeGui::FileTreeGui (QWidget *parent = \fC0\fP)"

.PP
Definition at line 10 of file FileTreeGui\&.cpp\&.
.SS "FileTreeGui::~FileTreeGui ()"

.PP
Definition at line 200 of file FileTreeGui\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void FileTreeGui::addChildren (QTreeWidgetItem *item, QStringfilePath)\fC [static]\fP"

.PP
Definition at line 72 of file FileTreeGui\&.cpp\&.
.SS "QTabWidget * FileTreeGui::getMasterTabWidgetPtr ()"

.PP
Definition at line 194 of file FileTreeGui\&.cpp\&.
.SS "QString * FileTreeGui::getProjectRootAbsPathStrPtr ()\fC [static]\fP"

.PP
Definition at line 172 of file FileTreeGui\&.cpp\&.
.SS "void FileTreeGui::handleRightClickSlot (const QPoint &pos)\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 135 of file FileTreeGui\&.cpp\&.
.SS "void FileTreeGui::handleShowDirectorySlot (QTreeWidgetItem *item, intcolumn)\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 99 of file FileTreeGui\&.cpp\&.
.SS "void FileTreeGui::initTree ()\fC [static]\fP"

.PP
Definition at line 40 of file FileTreeGui\&.cpp\&.
.SS "void FileTreeGui::refresh ()\fC [static]\fP"

.PP
Definition at line 178 of file FileTreeGui\&.cpp\&.
.SS "void FileTreeGui::setMasterTabWidgetPtr (QTabWidget *masterTabWidgetPtr)"

.PP
Definition at line 188 of file FileTreeGui\&.cpp\&.
.SS "void FileTreeGui::setProjectRootAbsPathStrPtr (QString *projectRootAbsPathStrPtr)\fC [static]\fP"

.PP
Definition at line 166 of file FileTreeGui\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QTabWidget* FileTreeGui::masterTabWidgetPtr\fC [private]\fP"

.PP
Definition at line 46 of file FileTreeGui\&.h\&.
.SS "QGridLayout* FileTreeGui::outerLayout\fC [private]\fP"

.PP
Definition at line 43 of file FileTreeGui\&.h\&.
.SS "QString * FileTreeGui::projectRootAbsPathStrPtr\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 45 of file FileTreeGui\&.h\&.
.SS "QSplitter * FileTreeGui::splitter\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 41 of file FileTreeGui\&.h\&.
.SS "QTreeWidget * FileTreeGui::trueTree\fC [static]\fP, \fC [private]\fP"

.PP
Definition at line 40 of file FileTreeGui\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
