.TH "/home/james/NetBeansProjects/ride/src/FileTreeGui.h" 3 "Tue Jun 2 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/FileTreeGui.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QSplitter>\fP
.br
\fC#include <QTreeView>\fP
.br
\fC#include <QHeaderView>\fP
.br
\fC#include <QFileSystemModel>\fP
.br
\fC#include <QListView>\fP
.br
\fC#include <QStandardItemModel>\fP
.br
\fC#include <QPoint>\fP
.br
\fC#include <QGridLayout>\fP
.br
\fC#include <QMenu>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFileTreeGui\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
