.TH "/home/james/NetBeansProjects/ride/src/FileGui.h" 3 "Fri Jun 12 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/FileGui.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QTextEdit>\fP
.br
\fC#include <QPlainTextEdit>\fP
.br
\fC#include <QTextObject>\fP
.br
\fC#include <QPainter>\fP
.br
\fC#include <QCompleter>\fP
.br
\fC#include <QTextCursor>\fP
.br
\fC#include <QAbstractItemView>\fP
.br
\fC#include <QScrollBar>\fP
.br
\fC#include <QPaintEvent>\fP
.br
\fC#include <QResizeEvent>\fP
.br
\fC#include <QSize>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFileGui\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
