.TH "FileGui" 3 "Sat Jun 6 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileGui \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FileGui\&.h>\fP
.PP
Inherits QPlainTextEdit\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileGui\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetCompleter\fP (QCompleter *\fBc\fP)"
.br
.ti -1c
.RI "QCompleter * \fBcompleter\fP () const "
.br
.ti -1c
.RI "void \fBlineNumberAreaPaintEvent\fP (QPaintEvent *event)"
.br
.ti -1c
.RI "int \fBlineNumberAreaWidth\fP ()"
.br
.ti -1c
.RI "void \fBresizeEvent\fP (QResizeEvent *event)"
.br
.ti -1c
.RI "\fB~FileGui\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBkeyPressEvent\fP (QKeyEvent *e)"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBinsertCompletion\fP (const QString &completion)"
.br
.ti -1c
.RI "void \fBupdateLineNumberAreaWidth\fP (int newBlockCount)"
.br
.ti -1c
.RI "void \fBhighlightCurrentLine\fP ()"
.br
.ti -1c
.RI "void \fBupdateLineNumberArea\fP (const QRect &, int)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "QString \fBtextUnderCursor\fP () const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QWidget * \fBlineNumberArea\fP"
.br
.ti -1c
.RI "QCompleter * \fBc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file FileGui\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FileGui::FileGui (QWidget *parent = \fC0\fP)"

.PP
Definition at line 14 of file FileGui\&.cpp\&.
.SS "FileGui::~FileGui ()"

.PP
Definition at line 215 of file FileGui\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QCompleter * FileGui::completer () const"

.PP
Definition at line 50 of file FileGui\&.cpp\&.
.SS "void FileGui::highlightCurrentLine ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 164 of file FileGui\&.cpp\&.
.SS "void FileGui::insertCompletion (const QString &completion)\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 56 of file FileGui\&.cpp\&.
.SS "void FileGui::keyPressEvent (QKeyEvent *e)\fC [protected]\fP"

.PP
Definition at line 75 of file FileGui\&.cpp\&.
.SS "void FileGui::lineNumberAreaPaintEvent (QPaintEvent *event)"

.PP
Definition at line 185 of file FileGui\&.cpp\&.
.SS "int FileGui::lineNumberAreaWidth ()"

.PP
Definition at line 121 of file FileGui\&.cpp\&.
.SS "void FileGui::resizeEvent (QResizeEvent *event)"

.PP
Definition at line 155 of file FileGui\&.cpp\&.
.SS "void FileGui::setCompleter (QCompleter *c)"

.PP
Definition at line 31 of file FileGui\&.cpp\&.
.SS "QString FileGui::textUnderCursor () const\fC [private]\fP"

.PP
Definition at line 67 of file FileGui\&.cpp\&.
.SS "void FileGui::updateLineNumberArea (const QRect &rect, intdy)\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 143 of file FileGui\&.cpp\&.
.SS "void FileGui::updateLineNumberAreaWidth (intnewBlockCount)\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 137 of file FileGui\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QCompleter* FileGui::c\fC [private]\fP"

.PP
Definition at line 37 of file FileGui\&.h\&.
.SS "QWidget* FileGui::lineNumberArea\fC [private]\fP"

.PP
Definition at line 35 of file FileGui\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
