.TH "Highlighter::HighlightingRule" 3 "Tue Jun 2 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Highlighter::HighlightingRule \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QRegExp \fBpattern\fP"
.br
.ti -1c
.RI "QTextCharFormat \fBformat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file Highlighter\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "QTextCharFormat Highlighter::HighlightingRule::format"

.PP
Definition at line 26 of file Highlighter\&.h\&.
.SS "QRegExp Highlighter::HighlightingRule::pattern"

.PP
Definition at line 25 of file Highlighter\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
