.TH "LineNumberArea" 3 "Sat Jun 6 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LineNumberArea \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LineNumberArea\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLineNumberArea\fP (\fBFileGui\fP *parent=0)"
.br
.ti -1c
.RI "QSize \fBsizeHint\fP () const "
.br
.ti -1c
.RI "void \fBpaintEvent\fP (QPaintEvent *event)"
.br
.ti -1c
.RI "\fB~LineNumberArea\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBFileGui\fP * \fBfile\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file LineNumberArea\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LineNumberArea::LineNumberArea (\fBFileGui\fP *parent = \fC0\fP)"

.PP
Definition at line 48 of file LineNumberArea\&.cpp\&.
.SS "LineNumberArea::~LineNumberArea ()"

.PP
Definition at line 65 of file LineNumberArea\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void LineNumberArea::paintEvent (QPaintEvent *event)"

.PP
Definition at line 59 of file LineNumberArea\&.cpp\&.
.SS "QSize LineNumberArea::sizeHint () const"

.PP
Definition at line 54 of file LineNumberArea\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFileGui\fP* LineNumberArea::file\fC [private]\fP"

.PP
Definition at line 20 of file LineNumberArea\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
