.TH "/home/james/NetBeansProjects/ride/src/main.cpp" 3 "Tue Jun 2 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QApplication>\fP
.br
\fC#include 'MasterGui\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"

.PP
Definition at line 21 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
