.TH "/home/james/NetBeansProjects/ride/src/MasterToolBars.h" 3 "Tue Jun 2 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/MasterToolBars.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QToolBar>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'NewProjectGui\&.h'\fP
.br
\fC#include 'MasterActions\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMasterToolBars\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
