.TH "MasterMenus" 3 "Tue Jun 2 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MasterMenus \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MasterMenus\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMasterMenus\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetMasterActionsPtr\fP (\fBMasterActions\fP *\fBmasterActionsPtr\fP)"
.br
.ti -1c
.RI "\fBMasterActions\fP * \fBgetMasterActionsPtr\fP ()"
.br
.ti -1c
.RI "void \fBinitFileMenuPtr\fP (QMenu *menu)"
.br
.ti -1c
.RI "void \fBinitEditMenuPtr\fP (QMenu *menu)"
.br
.ti -1c
.RI "void \fBinitViewMenuPtr\fP (QMenu *menu)"
.br
.ti -1c
.RI "void \fBinitNavigateMenuPtr\fP (QMenu *menu)"
.br
.ti -1c
.RI "void \fBinitSourceMenuPtr\fP (QMenu *menu)"
.br
.ti -1c
.RI "void \fBinitRefactorMenuPtr\fP (QMenu *menu)"
.br
.ti -1c
.RI "void \fBinitRunMenuPtr\fP (QMenu *menu)"
.br
.ti -1c
.RI "void \fBinitDebugMenuPtr\fP (QMenu *menu)"
.br
.ti -1c
.RI "void \fBinitProfileMenuPtr\fP (QMenu *menu)"
.br
.ti -1c
.RI "void \fBinitTeamMenuPtr\fP (QMenu *menu)"
.br
.ti -1c
.RI "void \fBinitToolsMenuPtr\fP (QMenu *menu)"
.br
.ti -1c
.RI "void \fBinitWindowMenuPtr\fP (QMenu *menu)"
.br
.ti -1c
.RI "void \fBinitHelpMenuPtr\fP (QMenu *menu)"
.br
.ti -1c
.RI "\fB~MasterMenus\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBMasterActions\fP * \fBmasterActionsPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file MasterMenus\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MasterMenus::MasterMenus (QWidget *parent = \fC0\fP)"

.PP
Definition at line 4 of file MasterMenus\&.cpp\&.
.SS "MasterMenus::~MasterMenus ()"

.PP
Definition at line 103 of file MasterMenus\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBMasterActions\fP * MasterMenus::getMasterActionsPtr ()"

.PP
Definition at line 16 of file MasterMenus\&.cpp\&.
.SS "void MasterMenus::initDebugMenuPtr (QMenu *menu)"

.PP
Definition at line 67 of file MasterMenus\&.cpp\&.
.SS "void MasterMenus::initEditMenuPtr (QMenu *menu)"

.PP
Definition at line 30 of file MasterMenus\&.cpp\&.
.SS "void MasterMenus::initFileMenuPtr (QMenu *menu)"

.PP
Definition at line 22 of file MasterMenus\&.cpp\&.
.SS "void MasterMenus::initHelpMenuPtr (QMenu *menu)"

.PP
Definition at line 97 of file MasterMenus\&.cpp\&.
.SS "void MasterMenus::initNavigateMenuPtr (QMenu *menu)"

.PP
Definition at line 43 of file MasterMenus\&.cpp\&.
.SS "void MasterMenus::initProfileMenuPtr (QMenu *menu)"

.PP
Definition at line 73 of file MasterMenus\&.cpp\&.
.SS "void MasterMenus::initRefactorMenuPtr (QMenu *menu)"

.PP
Definition at line 55 of file MasterMenus\&.cpp\&.
.SS "void MasterMenus::initRunMenuPtr (QMenu *menu)"

.PP
Definition at line 61 of file MasterMenus\&.cpp\&.
.SS "void MasterMenus::initSourceMenuPtr (QMenu *menu)"

.PP
Definition at line 49 of file MasterMenus\&.cpp\&.
.SS "void MasterMenus::initTeamMenuPtr (QMenu *menu)"

.PP
Definition at line 79 of file MasterMenus\&.cpp\&.
.SS "void MasterMenus::initToolsMenuPtr (QMenu *menu)"

.PP
Definition at line 85 of file MasterMenus\&.cpp\&.
.SS "void MasterMenus::initViewMenuPtr (QMenu *menu)"

.PP
Definition at line 37 of file MasterMenus\&.cpp\&.
.SS "void MasterMenus::initWindowMenuPtr (QMenu *menu)"

.PP
Definition at line 91 of file MasterMenus\&.cpp\&.
.SS "void MasterMenus::setMasterActionsPtr (\fBMasterActions\fP *masterActionsPtr)"

.PP
Definition at line 10 of file MasterMenus\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBMasterActions\fP* MasterMenus::masterActionsPtr\fC [private]\fP"

.PP
Definition at line 26 of file MasterMenus\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
