.TH "MasterStatusBar" 3 "Fri Jun 12 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MasterStatusBar \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MasterStatusBar\&.h>\fP
.PP
Inherits QStatusBar\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMasterStatusBar\fP ()"
.br
.ti -1c
.RI "void \fBinitProgressBarPtr\fP ()"
.br
.ti -1c
.RI "\fB~MasterStatusBar\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QProgressBar * \fBprogressBarPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file MasterStatusBar\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MasterStatusBar::MasterStatusBar ()"

.PP
Definition at line 4 of file MasterStatusBar\&.cpp\&.
.SS "MasterStatusBar::~MasterStatusBar ()"

.PP
Definition at line 18 of file MasterStatusBar\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void MasterStatusBar::initProgressBarPtr ()"

.PP
Definition at line 10 of file MasterStatusBar\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QProgressBar* MasterStatusBar::progressBarPtr\fC [private]\fP"

.PP
Definition at line 21 of file MasterStatusBar\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
