.TH "MasterToolBars" 3 "Tue Jun 2 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MasterToolBars \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MasterToolBars\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMasterToolBars\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetMasterActionsPtr\fP (\fBMasterActions\fP *masterActionsPtr)"
.br
.ti -1c
.RI "\fBMasterActions\fP * \fBgetMasterActionsPtr\fP ()"
.br
.ti -1c
.RI "void \fBinitNorthGroupOneToolBar\fP (QToolBar *toolbarPtr)"
.br
.ti -1c
.RI "void \fBinitNorthGroupTwoToolBar\fP (QToolBar *toolbarPtr)"
.br
.ti -1c
.RI "void \fBinitNorthGroupThreeToolBar\fP (QToolBar *toolbarPtr)"
.br
.ti -1c
.RI "void \fBinitSouthGroupOneToolBar\fP (QToolBar *toolbarPtr)"
.br
.ti -1c
.RI "void \fBinitEastGroupOneToolBar\fP (QToolBar *toolbarPtr)"
.br
.ti -1c
.RI "void \fBinitWestGroupOneToolBar\fP (QToolBar *toolbarPtr)"
.br
.ti -1c
.RI "\fB~MasterToolBars\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBMasterActions\fP * \fBmasterActions\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file MasterToolBars\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MasterToolBars::MasterToolBars (QWidget *parent = \fC0\fP)"

.PP
Definition at line 4 of file MasterToolBars\&.cpp\&.
.SS "MasterToolBars::~MasterToolBars ()"

.PP
Definition at line 74 of file MasterToolBars\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBMasterActions\fP * MasterToolBars::getMasterActionsPtr ()"

.PP
Definition at line 15 of file MasterToolBars\&.cpp\&.
.SS "void MasterToolBars::initEastGroupOneToolBar (QToolBar *toolbarPtr)"

.PP
Definition at line 58 of file MasterToolBars\&.cpp\&.
.SS "void MasterToolBars::initNorthGroupOneToolBar (QToolBar *toolbarPtr)"

.PP
Definition at line 21 of file MasterToolBars\&.cpp\&.
.SS "void MasterToolBars::initNorthGroupThreeToolBar (QToolBar *toolbarPtr)"

.PP
Definition at line 38 of file MasterToolBars\&.cpp\&.
.SS "void MasterToolBars::initNorthGroupTwoToolBar (QToolBar *toolbarPtr)"

.PP
Definition at line 31 of file MasterToolBars\&.cpp\&.
.SS "void MasterToolBars::initSouthGroupOneToolBar (QToolBar *toolbarPtr)"

.PP
Definition at line 50 of file MasterToolBars\&.cpp\&.
.SS "void MasterToolBars::initWestGroupOneToolBar (QToolBar *toolbarPtr)"

.PP
Definition at line 67 of file MasterToolBars\&.cpp\&.
.SS "void MasterToolBars::setMasterActionsPtr (\fBMasterActions\fP *masterActionsPtr)"

.PP
Definition at line 9 of file MasterToolBars\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBMasterActions\fP* MasterToolBars::masterActions\fC [private]\fP"

.PP
Definition at line 29 of file MasterToolBars\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
