.TH "/home/james/NetBeansProjects/ride/src/ModifyCMakeLists.h" 3 "Sat Jun 6 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/ModifyCMakeLists.h \- 
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
