.TH "/home/james/NetBeansProjects/ride/src/ModifyManifest.h" 3 "Tue Jun 2 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/ModifyManifest.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMODIFY_MANIFESTPACKAGE_H\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MODIFY_MANIFESTPACKAGE_H"

.PP
Definition at line 9 of file ModifyManifest\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
