.TH "MsgFileDat" 3 "Fri Jun 12 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MsgFileDat \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MsgFileDat\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMsgFileDat\fP ()"
.br
.ti -1c
.RI "void \fBsetMsgFileNameStrPtr\fP (string *\fBmsgFileNameStrPtr\fP)"
.br
.ti -1c
.RI "string * \fBgetMsgFileNameStrPtr\fP ()"
.br
.ti -1c
.RI "void \fBsetMsgFileHeaderStrPtr\fP (string *\fBmsgFileHeaderStrPtr\fP)"
.br
.ti -1c
.RI "string * \fBgetMsgFileHeaderStrPtr\fP ()"
.br
.ti -1c
.RI "void \fBpushToMsgFieldDatPtrVecPtr\fP (\fBMsgFieldDat\fP *msgFieldDatPtr)"
.br
.ti -1c
.RI "\fBMsgFieldDat\fP * \fBpopFromMsgFieldDatPtrVecPtr\fP ()"
.br
.ti -1c
.RI "vector< \fBMsgFieldDat\fP * > * \fBgetMsgFieldDatPtrVecPtr\fP ()"
.br
.ti -1c
.RI "string * \fBtoString\fP ()"
.br
.ti -1c
.RI "\fB~MsgFileDat\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "string * \fBmsgFileNameStrPtr\fP"
.br
.ti -1c
.RI "string * \fBmsgFileHeaderStrPtr\fP"
.br
.ti -1c
.RI "vector< \fBMsgFieldDat\fP * > * \fBmsgFieldDatPtrVecPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file MsgFileDat\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MsgFileDat::MsgFileDat ()"

.PP
Definition at line 4 of file MsgFileDat\&.cpp\&.
.SS "MsgFileDat::~MsgFileDat ()"

.PP
Definition at line 77 of file MsgFileDat\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "vector< \fBMsgFieldDat\fP * > * MsgFileDat::getMsgFieldDatPtrVecPtr ()"

.PP
Definition at line 53 of file MsgFileDat\&.cpp\&.
.SS "string * MsgFileDat::getMsgFileHeaderStrPtr ()"

.PP
Definition at line 31 of file MsgFileDat\&.cpp\&.
.SS "string * MsgFileDat::getMsgFileNameStrPtr ()"

.PP
Definition at line 19 of file MsgFileDat\&.cpp\&.
.SS "\fBMsgFieldDat\fP * MsgFileDat::popFromMsgFieldDatPtrVecPtr ()"

.PP
Definition at line 43 of file MsgFileDat\&.cpp\&.
.SS "void MsgFileDat::pushToMsgFieldDatPtrVecPtr (\fBMsgFieldDat\fP *msgFieldDatPtr)"

.PP
Definition at line 37 of file MsgFileDat\&.cpp\&.
.SS "void MsgFileDat::setMsgFileHeaderStrPtr (string *msgFileHeaderStrPtr)"

.PP
Definition at line 25 of file MsgFileDat\&.cpp\&.
.SS "void MsgFileDat::setMsgFileNameStrPtr (string *msgFileNameStrPtr)"

.PP
Definition at line 13 of file MsgFileDat\&.cpp\&.
.SS "string * MsgFileDat::toString ()"

.PP
Definition at line 59 of file MsgFileDat\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "vector<\fBMsgFieldDat\fP*>* MsgFileDat::msgFieldDatPtrVecPtr\fC [private]\fP"

.PP
Definition at line 26 of file MsgFileDat\&.h\&.
.SS "string* MsgFileDat::msgFileHeaderStrPtr\fC [private]\fP"

.PP
Definition at line 25 of file MsgFileDat\&.h\&.
.SS "string* MsgFileDat::msgFileNameStrPtr\fC [private]\fP"

.PP
Definition at line 24 of file MsgFileDat\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
