.TH "/home/james/NetBeansProjects/ride/src/NavigatorGui.h" 3 "Fri Jun 12 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/NavigatorGui.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QListWidget>\fP
.br
\fC#include <QSplitter>\fP
.br
\fC#include <QTabWidget>\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include <QGridLayout>\fP
.br
\fC#include 'SearchWidget\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNavigatorGui\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
