.TH "/home/james/NetBeansProjects/ride/src/NavigatorGui.h" 3 "Tue Jun 2 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/NavigatorGui.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QTreeView>\fP
.br
\fC#include <QSplitter>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNavigatorGui\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
