.TH "NavigatorGui" 3 "Tue Jun 2 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NavigatorGui \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NavigatorGui\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNavigatorGui\fP ()"
.br
.ti -1c
.RI "\fB~NavigatorGui\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file NavigatorGui\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NavigatorGui::NavigatorGui ()"

.PP
Definition at line 4 of file NavigatorGui\&.cpp\&.
.SS "NavigatorGui::~NavigatorGui ()"

.PP
Definition at line 10 of file NavigatorGui\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
