.TH "/home/james/NetBeansProjects/ride/src/NewFileGui.cpp" 3 "Tue Jun 2 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/NewFileGui.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'NewFileGui\&.h'\fP
.br
\fC#include 'FileTreeGui\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
