.TH "NewFilePage_3" 3 "Fri Jun 12 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewFilePage_3 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NewFilePage_3\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNewFilePage_3\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetMsgCatagoryStrPtr\fP ()"
.br
.ti -1c
.RI "QString * \fBgetMsgCatagoryStrPtr\fP ()"
.br
.ti -1c
.RI "void \fBsetSpecificMsgStrPtr\fP ()"
.br
.ti -1c
.RI "QString * \fBgetSpecificMsgStrPtr\fP ()"
.br
.ti -1c
.RI "void \fBtriggerMutators\fP ()"
.br
.ti -1c
.RI "QString * \fBtoString\fP ()"
.br
.ti -1c
.RI "\fB~NewFilePage_3\fP ()"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBhandleSwapOptionsSlot\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QStringList * \fBmsgCatagoryStrLstPtr\fP"
.br
.ti -1c
.RI "QVector< QStringList * > \fBspecificMsgStrLstVec\fP"
.br
.ti -1c
.RI "QListWidget * \fBmsgCatagoryLwPtr\fP"
.br
.ti -1c
.RI "QListWidget * \fBspecificMsgLwPtr\fP"
.br
.ti -1c
.RI "QGridLayout * \fBouterLayoutPtr\fP"
.br
.ti -1c
.RI "QString * \fBmsgCatagoryStrPtr\fP"
.br
.ti -1c
.RI "QString * \fBspecificMsgStrPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file NewFilePage_3\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NewFilePage_3::NewFilePage_3 (QWidget *parent = \fC0\fP)"

.PP
Definition at line 4 of file NewFilePage_3\&.cpp\&.
.SS "NewFilePage_3::~NewFilePage_3 ()"

.PP
Definition at line 113 of file NewFilePage_3\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QString * NewFilePage_3::getMsgCatagoryStrPtr ()"

.PP
Definition at line 70 of file NewFilePage_3\&.cpp\&.
.SS "QString * NewFilePage_3::getSpecificMsgStrPtr ()"

.PP
Definition at line 89 of file NewFilePage_3\&.cpp\&.
.SS "void NewFilePage_3::handleSwapOptionsSlot ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 47 of file NewFilePage_3\&.cpp\&.
.SS "void NewFilePage_3::setMsgCatagoryStrPtr ()"

.PP
Definition at line 57 of file NewFilePage_3\&.cpp\&.
.SS "void NewFilePage_3::setSpecificMsgStrPtr ()"

.PP
Definition at line 76 of file NewFilePage_3\&.cpp\&.
.SS "QString * NewFilePage_3::toString ()"

.PP
Definition at line 102 of file NewFilePage_3\&.cpp\&.
.SS "void NewFilePage_3::triggerMutators ()"

.PP
Definition at line 95 of file NewFilePage_3\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QListWidget* NewFilePage_3::msgCatagoryLwPtr\fC [private]\fP"

.PP
Definition at line 32 of file NewFilePage_3\&.h\&.
.SS "QStringList* NewFilePage_3::msgCatagoryStrLstPtr\fC [private]\fP"

.PP
Definition at line 30 of file NewFilePage_3\&.h\&.
.SS "QString* NewFilePage_3::msgCatagoryStrPtr\fC [private]\fP"

.PP
Definition at line 37 of file NewFilePage_3\&.h\&.
.SS "QGridLayout* NewFilePage_3::outerLayoutPtr\fC [private]\fP"

.PP
Definition at line 35 of file NewFilePage_3\&.h\&.
.SS "QListWidget* NewFilePage_3::specificMsgLwPtr\fC [private]\fP"

.PP
Definition at line 33 of file NewFilePage_3\&.h\&.
.SS "QVector<QStringList*> NewFilePage_3::specificMsgStrLstVec\fC [private]\fP"

.PP
Definition at line 31 of file NewFilePage_3\&.h\&.
.SS "QString* NewFilePage_3::specificMsgStrPtr\fC [private]\fP"

.PP
Definition at line 38 of file NewFilePage_3\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
