.TH "NewFilePage_2" 3 "Tue Jun 2 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewFilePage_2 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NewFilePage_2\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNewFilePage_2\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetOptionStrPtr\fP ()"
.br
.ti -1c
.RI "QString * \fBgetOptionStrPtr\fP ()"
.br
.ti -1c
.RI "void \fBtriggerMutators\fP ()"
.br
.ti -1c
.RI "QString * \fBtoString\fP ()"
.br
.ti -1c
.RI "\fB~NewFilePage_2\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QButtonGroup * \fBbuttonGroupPtr\fP"
.br
.ti -1c
.RI "QGridLayout * \fBouterLayoutPtr\fP"
.br
.ti -1c
.RI "QString * \fBoptionStrPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file NewFilePage_2\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NewFilePage_2::NewFilePage_2 (QWidget *parent = \fC0\fP)"

.PP
Definition at line 4 of file NewFilePage_2\&.cpp\&.
.SS "NewFilePage_2::~NewFilePage_2 ()"

.PP
Definition at line 61 of file NewFilePage_2\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QString * NewFilePage_2::getOptionStrPtr ()"

.PP
Definition at line 40 of file NewFilePage_2\&.cpp\&.
.SS "void NewFilePage_2::setOptionStrPtr ()"

.PP
Definition at line 25 of file NewFilePage_2\&.cpp\&.
.SS "QString * NewFilePage_2::toString ()"

.PP
Definition at line 52 of file NewFilePage_2\&.cpp\&.
.SS "void NewFilePage_2::triggerMutators ()"

.PP
Definition at line 46 of file NewFilePage_2\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QButtonGroup* NewFilePage_2::buttonGroupPtr\fC [private]\fP"

.PP
Definition at line 28 of file NewFilePage_2\&.h\&.
.SS "QString* NewFilePage_2::optionStrPtr\fC [private]\fP"

.PP
Definition at line 32 of file NewFilePage_2\&.h\&.
.SS "QGridLayout* NewFilePage_2::outerLayoutPtr\fC [private]\fP"

.PP
Definition at line 30 of file NewFilePage_2\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
