.TH "NewFilePage_4" 3 "Fri Jun 12 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewFilePage_4 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NewFilePage_4\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNewFilePage_4\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBinitCore\fP ()"
.br
.ti -1c
.RI "void \fBsetFileNameStrPtr\fP ()"
.br
.ti -1c
.RI "QString * \fBgetFileNameStrPtr\fP ()"
.br
.ti -1c
.RI "void \fBsetFileExtStrPtr\fP ()"
.br
.ti -1c
.RI "QString * \fBgetFileExtStrPtr\fP ()"
.br
.ti -1c
.RI "void \fBsetProjectStrPtr\fP ()"
.br
.ti -1c
.RI "QString * \fBgetProjectStrPtr\fP ()"
.br
.ti -1c
.RI "void \fBsetLocStrPtr\fP ()"
.br
.ti -1c
.RI "QString * \fBgetLocStrPtr\fP ()"
.br
.ti -1c
.RI "void \fBsetFolderStrPtr\fP ()"
.br
.ti -1c
.RI "QString * \fBgetFolderStrPtr\fP ()"
.br
.ti -1c
.RI "void \fBsetCreatedFileStrPtr\fP ()"
.br
.ti -1c
.RI "QString * \fBgetCreatedFileStrPtr\fP ()"
.br
.ti -1c
.RI "void \fBtriggerMutators\fP ()"
.br
.ti -1c
.RI "QString * \fBtoString\fP ()"
.br
.ti -1c
.RI "\fB~NewFilePage_4\fP ()"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBhandleFolderPbPtrSlot\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QLineEdit * \fBfileNameLePtr\fP"
.br
.ti -1c
.RI "QStringList * \fBfileExtsStrLstPtr\fP"
.br
.ti -1c
.RI "QComboBox * \fBfileExtCbPtr\fP"
.br
.ti -1c
.RI "QCheckBox * \fBdefaultFileExtChbPtr\fP"
.br
.ti -1c
.RI "QLineEdit * \fBprojectLePtr\fP"
.br
.ti -1c
.RI "QComboBox * \fBlocCbPtr\fP"
.br
.ti -1c
.RI "QLineEdit * \fBfolderLePtr\fP"
.br
.ti -1c
.RI "QFileDialog * \fBfolderDialogPtr\fP"
.br
.ti -1c
.RI "QPushButton * \fBfolderPbPtr\fP"
.br
.ti -1c
.RI "QLineEdit * \fBcreatedFileLePtr\fP"
.br
.ti -1c
.RI "QGridLayout * \fBfolderLayoutPtr\fP"
.br
.ti -1c
.RI "QFormLayout * \fBformLayoutPtr\fP"
.br
.ti -1c
.RI "QGridLayout * \fBouterLayoutPtr\fP"
.br
.ti -1c
.RI "QString * \fBfileNameStrPtr\fP"
.br
.ti -1c
.RI "QString * \fBfileExtStrPtr\fP"
.br
.ti -1c
.RI "QString * \fBprojectStrPtr\fP"
.br
.ti -1c
.RI "QString * \fBlocStrPtr\fP"
.br
.ti -1c
.RI "QString * \fBfolderStrPtr\fP"
.br
.ti -1c
.RI "QString * \fBcreatedFileStrPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file NewFilePage_4\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NewFilePage_4::NewFilePage_4 (QWidget *parent = \fC0\fP)"

.PP
Definition at line 3 of file NewFilePage_4\&.cpp\&.
.SS "NewFilePage_4::~NewFilePage_4 ()"

.PP
Definition at line 203 of file NewFilePage_4\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QString * NewFilePage_4::getCreatedFileStrPtr ()"

.PP
Definition at line 169 of file NewFilePage_4\&.cpp\&.
.SS "QString * NewFilePage_4::getFileExtStrPtr ()"

.PP
Definition at line 92 of file NewFilePage_4\&.cpp\&.
.SS "QString * NewFilePage_4::getFileNameStrPtr ()"

.PP
Definition at line 80 of file NewFilePage_4\&.cpp\&.
.SS "QString * NewFilePage_4::getFolderStrPtr ()"

.PP
Definition at line 150 of file NewFilePage_4\&.cpp\&.
.SS "QString * NewFilePage_4::getLocStrPtr ()"

.PP
Definition at line 131 of file NewFilePage_4\&.cpp\&.
.SS "QString * NewFilePage_4::getProjectStrPtr ()"

.PP
Definition at line 111 of file NewFilePage_4\&.cpp\&.
.SS "void NewFilePage_4::handleFolderPbPtrSlot ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 44 of file NewFilePage_4\&.cpp\&.
.SS "void NewFilePage_4::initCore ()"

.PP
Definition at line 56 of file NewFilePage_4\&.cpp\&.
.SS "void NewFilePage_4::setCreatedFileStrPtr ()"

.PP
Definition at line 156 of file NewFilePage_4\&.cpp\&.
.SS "void NewFilePage_4::setFileExtStrPtr ()"

.PP
Definition at line 86 of file NewFilePage_4\&.cpp\&.
.SS "void NewFilePage_4::setFileNameStrPtr ()"

.PP
Definition at line 67 of file NewFilePage_4\&.cpp\&.
.SS "void NewFilePage_4::setFolderStrPtr ()"

.PP
Definition at line 137 of file NewFilePage_4\&.cpp\&.
.SS "void NewFilePage_4::setLocStrPtr ()"

.PP
Definition at line 117 of file NewFilePage_4\&.cpp\&.
.SS "void NewFilePage_4::setProjectStrPtr ()"

.PP
Definition at line 98 of file NewFilePage_4\&.cpp\&.
.SS "QString * NewFilePage_4::toString ()"

.PP
Definition at line 186 of file NewFilePage_4\&.cpp\&.
.SS "void NewFilePage_4::triggerMutators ()"

.PP
Definition at line 175 of file NewFilePage_4\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QLineEdit* NewFilePage_4::createdFileLePtr\fC [private]\fP"

.PP
Definition at line 41 of file NewFilePage_4\&.h\&.
.SS "QString* NewFilePage_4::createdFileStrPtr\fC [private]\fP"

.PP
Definition at line 52 of file NewFilePage_4\&.h\&.
.SS "QCheckBox* NewFilePage_4::defaultFileExtChbPtr\fC [private]\fP"

.PP
Definition at line 35 of file NewFilePage_4\&.h\&.
.SS "QComboBox* NewFilePage_4::fileExtCbPtr\fC [private]\fP"

.PP
Definition at line 34 of file NewFilePage_4\&.h\&.
.SS "QStringList* NewFilePage_4::fileExtsStrLstPtr\fC [private]\fP"

.PP
Definition at line 33 of file NewFilePage_4\&.h\&.
.SS "QString* NewFilePage_4::fileExtStrPtr\fC [private]\fP"

.PP
Definition at line 48 of file NewFilePage_4\&.h\&.
.SS "QLineEdit* NewFilePage_4::fileNameLePtr\fC [private]\fP"

.PP
Definition at line 32 of file NewFilePage_4\&.h\&.
.SS "QString* NewFilePage_4::fileNameStrPtr\fC [private]\fP"

.PP
Definition at line 47 of file NewFilePage_4\&.h\&.
.SS "QFileDialog* NewFilePage_4::folderDialogPtr\fC [private]\fP"

.PP
Definition at line 39 of file NewFilePage_4\&.h\&.
.SS "QGridLayout* NewFilePage_4::folderLayoutPtr\fC [private]\fP"

.PP
Definition at line 43 of file NewFilePage_4\&.h\&.
.SS "QLineEdit* NewFilePage_4::folderLePtr\fC [private]\fP"

.PP
Definition at line 38 of file NewFilePage_4\&.h\&.
.SS "QPushButton* NewFilePage_4::folderPbPtr\fC [private]\fP"

.PP
Definition at line 40 of file NewFilePage_4\&.h\&.
.SS "QString* NewFilePage_4::folderStrPtr\fC [private]\fP"

.PP
Definition at line 51 of file NewFilePage_4\&.h\&.
.SS "QFormLayout* NewFilePage_4::formLayoutPtr\fC [private]\fP"

.PP
Definition at line 44 of file NewFilePage_4\&.h\&.
.SS "QComboBox* NewFilePage_4::locCbPtr\fC [private]\fP"

.PP
Definition at line 37 of file NewFilePage_4\&.h\&.
.SS "QString* NewFilePage_4::locStrPtr\fC [private]\fP"

.PP
Definition at line 50 of file NewFilePage_4\&.h\&.
.SS "QGridLayout* NewFilePage_4::outerLayoutPtr\fC [private]\fP"

.PP
Definition at line 45 of file NewFilePage_4\&.h\&.
.SS "QLineEdit* NewFilePage_4::projectLePtr\fC [private]\fP"

.PP
Definition at line 36 of file NewFilePage_4\&.h\&.
.SS "QString* NewFilePage_4::projectStrPtr\fC [private]\fP"

.PP
Definition at line 49 of file NewFilePage_4\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
