.TH "/home/james/NetBeansProjects/ride/src/NewFileGui.h" 3 "Fri Jun 12 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/NewFileGui.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QLineEdit>\fP
.br
\fC#include <QComboBox>\fP
.br
\fC#include <QCheckBox>\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include <QTabWidget>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QCompleter>\fP
.br
\fC#include <QAbstractItemModel>\fP
.br
\fC#include <QTextEdit>\fP
.br
\fC#include <QByteArray>\fP
.br
\fC#include <QPlainTextEdit>\fP
.br
\fC#include <QProgressBar>\fP
.br
\fC#include <QApplication>\fP
.br
\fC#include <QMainWindow>\fP
.br
\fC#include <QFormLayout>\fP
.br
\fC#include <QGridLayout>\fP
.br
\fC#include 'FileGui\&.h'\fP
.br
\fC#include 'RideFile\&.h'\fP
.br
\fC#include 'Highlighter\&.h'\fP
.br
\fC#include 'NewFilePage_1\&.h'\fP
.br
\fC#include 'NewFilePage_2\&.h'\fP
.br
\fC#include 'NewFilePage_3\&.h'\fP
.br
\fC#include 'NewFilePage_4\&.h'\fP
.br
\fC#include 'SaveAll\&.h'\fP
.br
\fC#include 'FileTreeGui\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNewFileGui\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
