.TH "NewProjectPage_1" 3 "Tue Jun 2 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewProjectPage_1 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NewProjectPage_1\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNewProjectPage_1\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetRosVersionStrPtr\fP ()"
.br
.ti -1c
.RI "QString * \fBgetRosVersionStrPtr\fP ()"
.br
.ti -1c
.RI "void \fBtriggerMutators\fP ()"
.br
.ti -1c
.RI "QString * \fBtoString\fP ()"
.br
.ti -1c
.RI "\fB~NewProjectPage_1\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QStringList * \fBrosVersionsStrLstPtr\fP"
.br
.ti -1c
.RI "QListWidget * \fBrosVersionsLwPtr\fP"
.br
.ti -1c
.RI "QGridLayout * \fBouterLayoutPtr\fP"
.br
.ti -1c
.RI "QString * \fBrosVersionStrPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file NewProjectPage_1\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NewProjectPage_1::NewProjectPage_1 (QWidget *parent = \fC0\fP)"

.PP
Definition at line 4 of file NewProjectPage_1\&.cpp\&.
.SS "NewProjectPage_1::~NewProjectPage_1 ()"

.PP
Definition at line 59 of file NewProjectPage_1\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QString * NewProjectPage_1::getRosVersionStrPtr ()"

.PP
Definition at line 38 of file NewProjectPage_1\&.cpp\&.
.SS "void NewProjectPage_1::setRosVersionStrPtr ()"

.PP
Definition at line 25 of file NewProjectPage_1\&.cpp\&.
.SS "QString * NewProjectPage_1::toString ()"

.PP
Definition at line 44 of file NewProjectPage_1\&.cpp\&.
.SS "void NewProjectPage_1::triggerMutators ()"

.PP
Definition at line 53 of file NewProjectPage_1\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QGridLayout* NewProjectPage_1::outerLayoutPtr\fC [private]\fP"

.PP
Definition at line 31 of file NewProjectPage_1\&.h\&.
.SS "QListWidget* NewProjectPage_1::rosVersionsLwPtr\fC [private]\fP"

.PP
Definition at line 29 of file NewProjectPage_1\&.h\&.
.SS "QStringList* NewProjectPage_1::rosVersionsStrLstPtr\fC [private]\fP"

.PP
Definition at line 28 of file NewProjectPage_1\&.h\&.
.SS "QString* NewProjectPage_1::rosVersionStrPtr\fC [private]\fP"

.PP
Definition at line 33 of file NewProjectPage_1\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
