.TH "NewProjectPage_2" 3 "Fri Jun 12 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewProjectPage_2 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NewProjectPage_2\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNewProjectPage_2\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetProjectNameStrPtr\fP ()"
.br
.ti -1c
.RI "QString * \fBgetProjectNameStrPtr\fP ()"
.br
.ti -1c
.RI "void \fBsetProjectLocStrPtr\fP ()"
.br
.ti -1c
.RI "QString * \fBgetProjectLocStrPtr\fP ()"
.br
.ti -1c
.RI "void \fBsetProjectTypeStrPtr\fP ()"
.br
.ti -1c
.RI "QString * \fBgetProjectTypeStrPtr\fP ()"
.br
.ti -1c
.RI "void \fBtriggerMutators\fP ()"
.br
.ti -1c
.RI "QString * \fBtoString\fP ()"
.br
.ti -1c
.RI "\fB~NewProjectPage_2\fP ()"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBhandleLocPbPtrSlot\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QLineEdit * \fBprojectNameLePtr\fP"
.br
.ti -1c
.RI "QLineEdit * \fBprojectLocLePtr\fP"
.br
.ti -1c
.RI "QFileDialog * \fBdirDialogPtr\fP"
.br
.ti -1c
.RI "QPushButton * \fBlocPbPtr\fP"
.br
.ti -1c
.RI "QStringList * \fBprojectTypeStrList\fP"
.br
.ti -1c
.RI "QListWidget * \fBprojectTypeLwPtr\fP"
.br
.ti -1c
.RI "QGridLayout * \fBlocationLayout\fP"
.br
.ti -1c
.RI "QFormLayout * \fBformLayout\fP"
.br
.ti -1c
.RI "QGridLayout * \fBouterLayout\fP"
.br
.ti -1c
.RI "QString * \fBprojectNameStrPtr\fP"
.br
.ti -1c
.RI "QString * \fBprojectLocStrPtr\fP"
.br
.ti -1c
.RI "QString * \fBprojectTypeStrPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 27 of file NewProjectPage_2\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NewProjectPage_2::NewProjectPage_2 (QWidget *parent = \fC0\fP)"

.PP
Definition at line 4 of file NewProjectPage_2\&.cpp\&.
.SS "NewProjectPage_2::~NewProjectPage_2 ()"

.PP
Definition at line 128 of file NewProjectPage_2\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QString * NewProjectPage_2::getProjectLocStrPtr ()"

.PP
Definition at line 82 of file NewProjectPage_2\&.cpp\&.
.SS "QString * NewProjectPage_2::getProjectNameStrPtr ()"

.PP
Definition at line 63 of file NewProjectPage_2\&.cpp\&.
.SS "QString * NewProjectPage_2::getProjectTypeStrPtr ()"

.PP
Definition at line 101 of file NewProjectPage_2\&.cpp\&.
.SS "void NewProjectPage_2::handleLocPbPtrSlot ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 39 of file NewProjectPage_2\&.cpp\&.
.SS "void NewProjectPage_2::setProjectLocStrPtr ()"

.PP
Definition at line 69 of file NewProjectPage_2\&.cpp\&.
.SS "void NewProjectPage_2::setProjectNameStrPtr ()"

.PP
Definition at line 50 of file NewProjectPage_2\&.cpp\&.
.SS "void NewProjectPage_2::setProjectTypeStrPtr ()"

.PP
Definition at line 88 of file NewProjectPage_2\&.cpp\&.
.SS "QString * NewProjectPage_2::toString ()"

.PP
Definition at line 107 of file NewProjectPage_2\&.cpp\&.
.SS "void NewProjectPage_2::triggerMutators ()"

.PP
Definition at line 120 of file NewProjectPage_2\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QFileDialog* NewProjectPage_2::dirDialogPtr\fC [private]\fP"

.PP
Definition at line 34 of file NewProjectPage_2\&.h\&.
.SS "QFormLayout* NewProjectPage_2::formLayout\fC [private]\fP"

.PP
Definition at line 40 of file NewProjectPage_2\&.h\&.
.SS "QGridLayout* NewProjectPage_2::locationLayout\fC [private]\fP"

.PP
Definition at line 39 of file NewProjectPage_2\&.h\&.
.SS "QPushButton* NewProjectPage_2::locPbPtr\fC [private]\fP"

.PP
Definition at line 35 of file NewProjectPage_2\&.h\&.
.SS "QGridLayout* NewProjectPage_2::outerLayout\fC [private]\fP"

.PP
Definition at line 41 of file NewProjectPage_2\&.h\&.
.SS "QLineEdit* NewProjectPage_2::projectLocLePtr\fC [private]\fP"

.PP
Definition at line 33 of file NewProjectPage_2\&.h\&.
.SS "QString* NewProjectPage_2::projectLocStrPtr\fC [private]\fP"

.PP
Definition at line 44 of file NewProjectPage_2\&.h\&.
.SS "QLineEdit* NewProjectPage_2::projectNameLePtr\fC [private]\fP"

.PP
Definition at line 32 of file NewProjectPage_2\&.h\&.
.SS "QString* NewProjectPage_2::projectNameStrPtr\fC [private]\fP"

.PP
Definition at line 43 of file NewProjectPage_2\&.h\&.
.SS "QListWidget* NewProjectPage_2::projectTypeLwPtr\fC [private]\fP"

.PP
Definition at line 37 of file NewProjectPage_2\&.h\&.
.SS "QStringList* NewProjectPage_2::projectTypeStrList\fC [private]\fP"

.PP
Definition at line 36 of file NewProjectPage_2\&.h\&.
.SS "QString* NewProjectPage_2::projectTypeStrPtr\fC [private]\fP"

.PP
Definition at line 45 of file NewProjectPage_2\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
