.TH "/home/james/NetBeansProjects/ride/src/NewProjectGui.h" 3 "Fri Jun 12 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/NewProjectGui.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QListWidget>\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include <QStringList>\fP
.br
\fC#include <QByteArray>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QIcon>\fP
.br
\fC#include <QProcess>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QGridLayout>\fP
.br
\fC#include <QHBoxLayout>\fP
.br
\fC#include 'NewProjectPage_1\&.h'\fP
.br
\fC#include 'NewProjectPage_2\&.h'\fP
.br
\fC#include 'NewProjectPage_3\&.h'\fP
.br
\fC#include 'NewProjectPage_4\&.h'\fP
.br
\fC#include 'RideFile\&.h'\fP
.br
\fC#include 'FileTreeGui\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNewProjectGui\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
