.TH "NewProjectPage_4" 3 "Fri Jun 12 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewProjectPage_4 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <NewProjectPage_4\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNewProjectPage_4\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "QStringList * \fBgetDependsEnteredStrList\fP ()"
.br
.ti -1c
.RI "QString * \fBtoString\fP ()"
.br
.ti -1c
.RI "\fB~NewProjectPage_4\fP ()"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBhandleAddToListBtnPtrSlot\fP ()"
.br
.ti -1c
.RI "void \fBhandleRmFromListBtnPtrSlot\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QStringList * \fBdependsEnteredStrList\fP"
.br
.ti -1c
.RI "QLineEdit * \fBdependsLePtr\fP"
.br
.ti -1c
.RI "QPushButton * \fBaddToListBtnPtr\fP"
.br
.ti -1c
.RI "QListWidget * \fBdependsEnteredTypeLw\fP"
.br
.ti -1c
.RI "QPushButton * \fBrmFromListBtnPtr\fP"
.br
.ti -1c
.RI "QGridLayout * \fBouterLayout\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file NewProjectPage_4\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NewProjectPage_4::NewProjectPage_4 (QWidget *parent = \fC0\fP)"

.PP
Definition at line 4 of file NewProjectPage_4\&.cpp\&.
.SS "NewProjectPage_4::~NewProjectPage_4 ()"

.PP
Definition at line 93 of file NewProjectPage_4\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QStringList * NewProjectPage_4::getDependsEnteredStrList ()"

.PP
Definition at line 73 of file NewProjectPage_4\&.cpp\&.
.SS "void NewProjectPage_4::handleAddToListBtnPtrSlot ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 28 of file NewProjectPage_4\&.cpp\&.
.SS "void NewProjectPage_4::handleRmFromListBtnPtrSlot ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 55 of file NewProjectPage_4\&.cpp\&.
.SS "QString * NewProjectPage_4::toString ()"

.PP
Definition at line 79 of file NewProjectPage_4\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QPushButton* NewProjectPage_4::addToListBtnPtr\fC [private]\fP"

.PP
Definition at line 32 of file NewProjectPage_4\&.h\&.
.SS "QStringList* NewProjectPage_4::dependsEnteredStrList\fC [private]\fP"

.PP
Definition at line 30 of file NewProjectPage_4\&.h\&.
.SS "QListWidget* NewProjectPage_4::dependsEnteredTypeLw\fC [private]\fP"

.PP
Definition at line 33 of file NewProjectPage_4\&.h\&.
.SS "QLineEdit* NewProjectPage_4::dependsLePtr\fC [private]\fP"

.PP
Definition at line 31 of file NewProjectPage_4\&.h\&.
.SS "QGridLayout* NewProjectPage_4::outerLayout\fC [private]\fP"

.PP
Definition at line 36 of file NewProjectPage_4\&.h\&.
.SS "QPushButton* NewProjectPage_4::rmFromListBtnPtr\fC [private]\fP"

.PP
Definition at line 34 of file NewProjectPage_4\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
