.TH "OpeningGui" 3 "Fri Jun 12 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpeningGui \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OpeningGui\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOpeningGui\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~OpeningGui\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QLabel * \fBapplicationNameLabelPtr\fP"
.br
.ti -1c
.RI "QLabel * \fBappLabelPtr\fP"
.br
.ti -1c
.RI "QLabel * \fBapplicationNameIconLabelPtr\fP"
.br
.ti -1c
.RI "QLabel * \fBgithubLabelPtr\fP"
.br
.ti -1c
.RI "QGridLayout * \fBouterLayoutPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file OpeningGui\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OpeningGui::OpeningGui (QWidget *parent = \fC0\fP)"

.PP
Definition at line 3 of file OpeningGui\&.cpp\&.
.SS "OpeningGui::~OpeningGui ()"

.PP
Definition at line 38 of file OpeningGui\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QLabel* OpeningGui::appLabelPtr\fC [private]\fP"

.PP
Definition at line 24 of file OpeningGui\&.h\&.
.SS "QLabel* OpeningGui::applicationNameIconLabelPtr\fC [private]\fP"

.PP
Definition at line 25 of file OpeningGui\&.h\&.
.SS "QLabel* OpeningGui::applicationNameLabelPtr\fC [private]\fP"

.PP
Definition at line 23 of file OpeningGui\&.h\&.
.SS "QLabel* OpeningGui::githubLabelPtr\fC [private]\fP"

.PP
Definition at line 26 of file OpeningGui\&.h\&.
.SS "QGridLayout* OpeningGui::outerLayoutPtr\fC [private]\fP"

.PP
Definition at line 27 of file OpeningGui\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
