.TH "/home/james/NetBeansProjects/ride/src/OpenProjectGui.h" 3 "Tue Jun 2 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/OpenProjectGui.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QLineEdit>\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QHBoxLayout>\fP
.br
\fC#include <QGridLayout>\fP
.br
\fC#include 'FileTreeGui\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBOpenProjectGui\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
