.TH "/home/james/NetBeansProjects/ride/src/OpeningGui.cpp" 3 "Fri Jun 12 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/OpeningGui.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'OpeningGui\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
