.TH "ParseFontConfigXml" 3 "Fri Jun 12 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParseFontConfigXml \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ParseFontConfigXml\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParseFontConfigXml\fP ()"
.br
.ti -1c
.RI "void \fBloadFile\fP ()"
.br
.ti -1c
.RI "void \fBreadDoc\fP ()"
.br
.ti -1c
.RI "void \fBparseDoc\fP ()"
.br
.ti -1c
.RI "\fB~ParseFontConfigXml\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QFile * \fBfilePtr\fP"
.br
.ti -1c
.RI "QDomDocument * \fBxmlDomDocPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file ParseFontConfigXml\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ParseFontConfigXml::ParseFontConfigXml ()"

.PP
Definition at line 4 of file ParseFontConfigXml\&.cpp\&.
.SS "ParseFontConfigXml::~ParseFontConfigXml ()"

.PP
Definition at line 69 of file ParseFontConfigXml\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void ParseFontConfigXml::loadFile ()"

.PP
Definition at line 10 of file ParseFontConfigXml\&.cpp\&.
.SS "void ParseFontConfigXml::parseDoc ()"

.SS "void ParseFontConfigXml::readDoc ()"

.PP
Definition at line 27 of file ParseFontConfigXml\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QFile* ParseFontConfigXml::filePtr\fC [private]\fP"

.PP
Definition at line 22 of file ParseFontConfigXml\&.h\&.
.SS "QDomDocument* ParseFontConfigXml::xmlDomDocPtr\fC [private]\fP"

.PP
Definition at line 23 of file ParseFontConfigXml\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
