.TH "PhysicalAttribLog" 3 "Fri Jun 12 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhysicalAttribLog \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PhysicalAttribLog\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPhysicalAttribLog\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~PhysicalAttribLog\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file PhysicalAttribLog\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PhysicalAttribLog::PhysicalAttribLog (QWidget *parent = \fC0\fP)"

.PP
Definition at line 4 of file PhysicalAttribLog\&.cpp\&.
.SS "PhysicalAttribLog::~PhysicalAttribLog ()"

.PP
Definition at line 10 of file PhysicalAttribLog\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
