.TH "/home/james/NetBeansProjects/ride/src/RideFont.h" 3 "Tue Jun 2 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/RideFont.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QFont>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBRideFont\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBRideFont::initDefaultValues\fP ()"
.br
.ti -1c
.RI "void \fBRideFont::setFamily\fP (QString *fontName)"
.br
.ti -1c
.RI "QString * \fBRideFont::getFamily\fP ()"
.br
.ti -1c
.RI "void \fBRideFont::setFixedPitch\fP (bool isFixedPitch)"
.br
.ti -1c
.RI "bool \fBRideFont::getFixedPitch\fP ()"
.br
.ti -1c
.RI "void \fBRideFont::setPointSize\fP (int pointSize)"
.br
.ti -1c
.RI "int \fBRideFont::getPointSize\fP ()"
.br
.ti -1c
.RI "void \fBRideFont::setWeight\fP (int fontWeight)"
.br
.ti -1c
.RI "int \fBRideFont::getWeight\fP ()"
.br
.ti -1c
.RI "QString * \fBRideFont::toString\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "QFont * \fBRideFont::font\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
