.TH "RideFile" 3 "Sat Jun 6 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RideFile \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RideFile\&.h>\fP
.PP
Inherits QFile\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRideFile\fP ()"
.br
.ti -1c
.RI "\fBRideFile\fP (QString name)"
.br
.ti -1c
.RI "void \fBsetFileLangPtr\fP (\fBFileLang\fP *\fBfileLangPtr\fP)"
.br
.ti -1c
.RI "\fBFileLang\fP * \fBgetFileLangPtr\fP ()"
.br
.ti -1c
.RI "void \fBsetFileTypePtr\fP (\fBFileType\fP *\fBfileTypePtr\fP)"
.br
.ti -1c
.RI "\fBFileType\fP * \fBgetFileTypePtr\fP ()"
.br
.ti -1c
.RI "void \fBsetFileNameStrPtr\fP (QString *\fBfileNameStrPtr\fP)"
.br
.ti -1c
.RI "QString * \fBgetFileNameStrPtr\fP ()"
.br
.ti -1c
.RI "void \fBsetFileExtStrPtr\fP (QString *\fBfileExtStrPtr\fP)"
.br
.ti -1c
.RI "QString * \fBgetFileExtStrPtr\fP ()"
.br
.ti -1c
.RI "void \fBsetAbsFilePathStrPtr\fP (QString *\fBabsFilePathStrPtr\fP)"
.br
.ti -1c
.RI "QString * \fBgetAbsFilePathStrPtr\fP ()"
.br
.ti -1c
.RI "void \fBsetRelFilePathStrPtr\fP (QString *\fBrelFilePathStrPtr\fP)"
.br
.ti -1c
.RI "QString * \fBgetRelFilePathStrPtr\fP ()"
.br
.ti -1c
.RI "void \fBsetParallelFileGuiPtr\fP (\fBFileGui\fP *\fBparallelFileGuiPtr\fP)"
.br
.ti -1c
.RI "\fBFileGui\fP * \fBgetParallelFileGuiPtr\fP ()"
.br
.ti -1c
.RI "bool \fBopenRdFile\fP ()"
.br
.ti -1c
.RI "bool \fBopenWrFile\fP ()"
.br
.ti -1c
.RI "bool \fBopenRdWrFile\fP ()"
.br
.ti -1c
.RI "QString * \fBreadFile\fP ()"
.br
.ti -1c
.RI "bool \fBwriteFile\fP (QString *text)"
.br
.ti -1c
.RI "bool \fBcloseFile\fP ()"
.br
.ti -1c
.RI "QString * \fBtoString\fP ()"
.br
.ti -1c
.RI "\fB~RideFile\fP ()"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "enum \fBFileLang\fP { \fBC\fP, \fBCPP\fP, \fBPYTHON\fP, \fBJAVA\fP, \fBLISP\fP, \fBSHELL\fP, \fBOTHER\fP }"
.br
.ti -1c
.RI "enum \fBFileType\fP { \fBHEADER\fP, \fBSOURCE\fP, \fBDYN_CONFIG\fP, \fBPACKAGE\fP, \fBCMAKELISTS\fP, \fBBASH_SHELL\fP, \fBBOURNE_SHELL\fP, \fBC_SHELL\fP, \fBKORN_SHELL\fP, \fBZ_SHELL\fP, \fBXML\fP, \fBJSON\fP, \fBDB\fP, \fBYAML\fP, \fBCSS\fP, \fBTEXT\fP, \fBEMPTY\fP }"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "QByteArray * \fBtoQByteArray\fP (QString *string)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBFileLang\fP * \fBfileLangPtr\fP"
.br
.ti -1c
.RI "\fBFileType\fP * \fBfileTypePtr\fP"
.br
.ti -1c
.RI "QString * \fBfileNameStrPtr\fP"
.br
.ti -1c
.RI "QString * \fBfileExtStrPtr\fP"
.br
.ti -1c
.RI "QString * \fBabsFilePathStrPtr\fP"
.br
.ti -1c
.RI "QString * \fBrelFilePathStrPtr\fP"
.br
.ti -1c
.RI "\fBFileGui\fP * \fBparallelFileGuiPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file RideFile\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBRideFile::FileLang\fP\fC [private]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIC \fP\fP
.TP
\fB\fICPP \fP\fP
.TP
\fB\fIPYTHON \fP\fP
.TP
\fB\fIJAVA \fP\fP
.TP
\fB\fILISP \fP\fP
.TP
\fB\fISHELL \fP\fP
.TP
\fB\fIOTHER \fP\fP
.PP
Definition at line 31 of file RideFile\&.h\&.
.SS "enum \fBRideFile::FileType\fP\fC [private]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIHEADER \fP\fP
.TP
\fB\fISOURCE \fP\fP
.TP
\fB\fIDYN_CONFIG \fP\fP
.TP
\fB\fIPACKAGE \fP\fP
.TP
\fB\fICMAKELISTS \fP\fP
.TP
\fB\fIBASH_SHELL \fP\fP
.TP
\fB\fIBOURNE_SHELL \fP\fP
.TP
\fB\fIC_SHELL \fP\fP
.TP
\fB\fIKORN_SHELL \fP\fP
.TP
\fB\fIZ_SHELL \fP\fP
.TP
\fB\fIXML \fP\fP
.TP
\fB\fIJSON \fP\fP
.TP
\fB\fIDB \fP\fP
.TP
\fB\fIYAML \fP\fP
.TP
\fB\fICSS \fP\fP
.TP
\fB\fITEXT \fP\fP
.TP
\fB\fIEMPTY \fP\fP
.PP
Definition at line 42 of file RideFile\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RideFile::RideFile ()"

.PP
Definition at line 4 of file RideFile\&.cpp\&.
.SS "RideFile::RideFile (QStringname)"

.PP
Definition at line 10 of file RideFile\&.cpp\&.
.SS "RideFile::~RideFile ()"

.PP
Definition at line 188 of file RideFile\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool RideFile::closeFile ()"

.PP
Definition at line 149 of file RideFile\&.cpp\&.
.SS "QString * RideFile::getAbsFilePathStrPtr ()"

.PP
Definition at line 70 of file RideFile\&.cpp\&.
.SS "QString * RideFile::getFileExtStrPtr ()"

.PP
Definition at line 58 of file RideFile\&.cpp\&.
.SS "\fBRideFile::FileLang\fP * RideFile::getFileLangPtr ()"

.PP
Definition at line 22 of file RideFile\&.cpp\&.
.SS "QString * RideFile::getFileNameStrPtr ()"

.PP
Definition at line 46 of file RideFile\&.cpp\&.
.SS "\fBRideFile::FileType\fP * RideFile::getFileTypePtr ()"

.PP
Definition at line 34 of file RideFile\&.cpp\&.
.SS "\fBFileGui\fP * RideFile::getParallelFileGuiPtr ()"

.PP
Definition at line 94 of file RideFile\&.cpp\&.
.SS "QString * RideFile::getRelFilePathStrPtr ()"

.PP
Definition at line 82 of file RideFile\&.cpp\&.
.SS "bool RideFile::openRdFile ()"

.PP
Definition at line 100 of file RideFile\&.cpp\&.
.SS "bool RideFile::openRdWrFile ()"

.PP
Definition at line 123 of file RideFile\&.cpp\&.
.SS "bool RideFile::openWrFile ()"

.PP
Definition at line 112 of file RideFile\&.cpp\&.
.SS "QString * RideFile::readFile ()"

.PP
Definition at line 135 of file RideFile\&.cpp\&.
.SS "void RideFile::setAbsFilePathStrPtr (QString *absFilePathStrPtr)"

.PP
Definition at line 64 of file RideFile\&.cpp\&.
.SS "void RideFile::setFileExtStrPtr (QString *fileExtStrPtr)"

.PP
Definition at line 52 of file RideFile\&.cpp\&.
.SS "void RideFile::setFileLangPtr (\fBFileLang\fP *fileLangPtr)"

.PP
Definition at line 16 of file RideFile\&.cpp\&.
.SS "void RideFile::setFileNameStrPtr (QString *fileNameStrPtr)"

.PP
Definition at line 40 of file RideFile\&.cpp\&.
.SS "void RideFile::setFileTypePtr (\fBFileType\fP *fileTypePtr)"

.PP
Definition at line 28 of file RideFile\&.cpp\&.
.SS "void RideFile::setParallelFileGuiPtr (\fBFileGui\fP *parallelFileGuiPtr)"

.PP
Definition at line 88 of file RideFile\&.cpp\&.
.SS "void RideFile::setRelFilePathStrPtr (QString *relFilePathStrPtr)"

.PP
Definition at line 76 of file RideFile\&.cpp\&.
.SS "QByteArray * RideFile::toQByteArray (QString *string)\fC [private]\fP"

.PP
Definition at line 161 of file RideFile\&.cpp\&.
.SS "QString * RideFile::toString ()"

.PP
Definition at line 174 of file RideFile\&.cpp\&.
.SS "bool RideFile::writeFile (QString *text)"

.PP
Definition at line 141 of file RideFile\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QString* RideFile::absFilePathStrPtr\fC [private]\fP"

.PP
Definition at line 67 of file RideFile\&.h\&.
.SS "QString* RideFile::fileExtStrPtr\fC [private]\fP"

.PP
Definition at line 66 of file RideFile\&.h\&.
.SS "\fBFileLang\fP* RideFile::fileLangPtr\fC [private]\fP"

.PP
Definition at line 63 of file RideFile\&.h\&.
.SS "QString* RideFile::fileNameStrPtr\fC [private]\fP"

.PP
Definition at line 65 of file RideFile\&.h\&.
.SS "\fBFileType\fP* RideFile::fileTypePtr\fC [private]\fP"

.PP
Definition at line 64 of file RideFile\&.h\&.
.SS "\fBFileGui\fP* RideFile::parallelFileGuiPtr\fC [private]\fP"

.PP
Definition at line 70 of file RideFile\&.h\&.
.SS "QString* RideFile::relFilePathStrPtr\fC [private]\fP"

.PP
Definition at line 68 of file RideFile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
