.TH "RideEnv" 3 "Fri Jun 12 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RideEnv \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RideEnv\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRideEnv\fP ()"
.br
.ti -1c
.RI "void \fBsetCatkinWsAbsPathStrPtr\fP (QString *\fBcatkinWsAbsPathStrPtr\fP)"
.br
.ti -1c
.RI "QString * \fBgetCatkinWsAbsPathStrPtr\fP ()"
.br
.ti -1c
.RI "void \fBpushToNodeAbsPathStrLstPtr\fP (QString *nodeAbsPathStr)"
.br
.ti -1c
.RI "QString * \fBpopFromNodeAbsPathStrLstPtr\fP ()"
.br
.ti -1c
.RI "QStringList * \fBgetNodeAbsPathStrLstPtr\fP ()"
.br
.ti -1c
.RI "void \fBsetRideProjDirAbsPathStrPtr\fP (QString *\fBrideProjDirAbsPathStrPtr\fP)"
.br
.ti -1c
.RI "QString * \fBgetRideProjDirAbsPathStrPtr\fP ()"
.br
.ti -1c
.RI "QString * \fBtoString\fP ()"
.br
.ti -1c
.RI "\fB~RideEnv\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QString * \fBcatkinWsAbsPathStrPtr\fP"
.br
.ti -1c
.RI "QStringList * \fBnodeAbsPathStrLstPtr\fP"
.br
.ti -1c
.RI "QString * \fBrideProjDirAbsPathStrPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file RideEnv\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RideEnv::RideEnv ()"

.PP
Definition at line 4 of file RideEnv\&.cpp\&.
.SS "RideEnv::~RideEnv ()"

.PP
Definition at line 66 of file RideEnv\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QString * RideEnv::getCatkinWsAbsPathStrPtr ()"

.PP
Definition at line 18 of file RideEnv\&.cpp\&.
.SS "QStringList * RideEnv::getNodeAbsPathStrLstPtr ()"

.PP
Definition at line 39 of file RideEnv\&.cpp\&.
.SS "QString * RideEnv::getRideProjDirAbsPathStrPtr ()"

.PP
Definition at line 51 of file RideEnv\&.cpp\&.
.SS "QString * RideEnv::popFromNodeAbsPathStrLstPtr ()"

.PP
Definition at line 30 of file RideEnv\&.cpp\&.
.SS "void RideEnv::pushToNodeAbsPathStrLstPtr (QString *nodeAbsPathStr)"

.PP
Definition at line 24 of file RideEnv\&.cpp\&.
.SS "void RideEnv::setCatkinWsAbsPathStrPtr (QString *catkinWsAbsPathStrPtr)"

.PP
Definition at line 12 of file RideEnv\&.cpp\&.
.SS "void RideEnv::setRideProjDirAbsPathStrPtr (QString *rideProjDirAbsPathStrPtr)"

.PP
Definition at line 45 of file RideEnv\&.cpp\&.
.SS "QString* RideEnv::toString ()"

.SH "Member Data Documentation"
.PP 
.SS "QString* RideEnv::catkinWsAbsPathStrPtr\fC [private]\fP"
Absolute path to the ROS catkin workspace being used\&. 
.PP
Definition at line 32 of file RideEnv\&.h\&.
.SS "QStringList* RideEnv::nodeAbsPathStrLstPtr\fC [private]\fP"
Absolute paths to the 'root' directory of each node\&. 
.PP
Definition at line 37 of file RideEnv\&.h\&.
.SS "QString* RideEnv::rideProjDirAbsPathStrPtr\fC [private]\fP"
Absolute path to the \&.ridePorject directory of each node\&. 
.PP
Definition at line 42 of file RideEnv\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
