.TH "/home/james/NetBeansProjects/ride/src/RideEnv.cpp" 3 "Fri Jun 12 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/RideEnv.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'RideEnv\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QString * \fBtoString\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QString* toString ()"

.PP
Definition at line 57 of file RideEnv\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
