.TH "RideFont" 3 "Fri Jun 12 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RideFont \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitDefaultValues\fP ()"
.br
.ti -1c
.RI "void \fBsetFamily\fP (QString *fontName)"
.br
.ti -1c
.RI "QString * \fBgetFamily\fP ()"
.br
.ti -1c
.RI "void \fBsetFixedPitch\fP (bool isFixedPitch)"
.br
.ti -1c
.RI "bool \fBgetFixedPitch\fP ()"
.br
.ti -1c
.RI "void \fBsetPointSize\fP (int pointSize)"
.br
.ti -1c
.RI "int \fBgetPointSize\fP ()"
.br
.ti -1c
.RI "void \fBsetWeight\fP (int fontWeight)"
.br
.ti -1c
.RI "int \fBgetWeight\fP ()"
.br
.ti -1c
.RI "QString * \fBtoString\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "QFont * \fBfont\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QString * RideFont::getFamily ()"

.PP
Definition at line 19 of file RideFont\&.cpp\&.
.SS "bool RideFont::getFixedPitch ()"

.PP
Definition at line 31 of file RideFont\&.cpp\&.
.SS "int RideFont::getPointSize ()"

.PP
Definition at line 43 of file RideFont\&.cpp\&.
.SS "int RideFont::getWeight ()"

.PP
Definition at line 55 of file RideFont\&.cpp\&.
.SS "void RideFont::initDefaultValues ()"

.PP
Definition at line 3 of file RideFont\&.cpp\&.
.SS "void RideFont::setFamily (QString *fontName)"

.PP
Definition at line 13 of file RideFont\&.cpp\&.
.SS "void RideFont::setFixedPitch (boolisFixedPitch)"

.PP
Definition at line 25 of file RideFont\&.cpp\&.
.SS "void RideFont::setPointSize (intpointSize)"

.PP
Definition at line 37 of file RideFont\&.cpp\&.
.SS "void RideFont::setWeight (intfontWeight)"

.PP
Definition at line 49 of file RideFont\&.cpp\&.
.SS "QString * RideFont::toString ()"

.PP
Definition at line 61 of file RideFont\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "QFont* RideFont::font"

.PP
Definition at line 17 of file RideFont\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
