.TH "RProcess" 3 "Fri Jun 12 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RProcess \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RProcess\&.h>\fP
.PP
Inherits QProcess\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRProcess\fP ()"
.br
.ti -1c
.RI "\fB~RProcess\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file RProcess\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RProcess::RProcess ()"

.PP
Definition at line 4 of file RProcess\&.cpp\&.
.SS "RProcess::~RProcess ()"

.PP
Definition at line 10 of file RProcess\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
