.TH "RunGui" 3 "Sat Jun 6 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RunGui \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RunGui\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRunGui\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBinitBtns\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "void \fBswapNextPage\fP ()"
.br
.ti -1c
.RI "void \fBswapBackPage\fP ()"
.br
.ti -1c
.RI "void \fBloadPage_1\fP ()"
.br
.ti -1c
.RI "void \fBunloadPage_1\fP ()"
.br
.ti -1c
.RI "void \fBloadPage_2\fP ()"
.br
.ti -1c
.RI "void \fBunloadPage_2\fP ()"
.br
.ti -1c
.RI "void \fBloadPage_3\fP ()"
.br
.ti -1c
.RI "void \fBunloadPage_3\fP ()"
.br
.ti -1c
.RI "QString * \fBtoString\fP ()"
.br
.ti -1c
.RI "\fB~RunGui\fP ()"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "enum \fBPage\fP { \fBPAGE_ONE\fP, \fBPAGE_TWO\fP, \fBPAGE_THREE\fP }"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBhandleBackBtnSlot\fP ()"
.br
.ti -1c
.RI "void \fBhandleNextBtnSlot\fP ()"
.br
.ti -1c
.RI "void \fBhandleFinishBtnSlot\fP ()"
.br
.ti -1c
.RI "void \fBhandleHelpBntSlot\fP ()"
.br
.ti -1c
.RI "void \fBhandleCancelBtnSlot\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBPage\fP \fBcurrentPage\fP"
.br
.ti -1c
.RI "QPushButton * \fBbackBtn\fP"
.br
.ti -1c
.RI "QPushButton * \fBnextBtn\fP"
.br
.ti -1c
.RI "QPushButton * \fBfinishBtn\fP"
.br
.ti -1c
.RI "QPushButton * \fBhelpBtn\fP"
.br
.ti -1c
.RI "QPushButton * \fBcancelBtn\fP"
.br
.ti -1c
.RI "QGridLayout * \fBouterLayoutPtr\fP"
.br
.ti -1c
.RI "QHBoxLayout * \fBbuttonLayout\fP"
.br
.ti -1c
.RI "\fBRunPage_1\fP * \fBrunPage_1Ptr\fP"
.br
.ti -1c
.RI "\fBRunPage_2\fP * \fBrunPage_2Ptr\fP"
.br
.ti -1c
.RI "\fBRunPage_3\fP * \fBrunPage_3Ptr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file RunGui\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBRunGui::Page\fP\fC [private]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPAGE_ONE \fP\fP
.TP
\fB\fIPAGE_TWO \fP\fP
.TP
\fB\fIPAGE_THREE \fP\fP
.PP
Definition at line 31 of file RunGui\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RunGui::RunGui (QWidget *parent = \fC0\fP)"

.PP
Definition at line 4 of file RunGui\&.cpp\&.
.SS "RunGui::~RunGui ()"

.PP
Definition at line 205 of file RunGui\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void RunGui::handleBackBtnSlot ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 22 of file RunGui\&.cpp\&.
.SS "void RunGui::handleCancelBtnSlot ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 46 of file RunGui\&.cpp\&.
.SS "void RunGui::handleFinishBtnSlot ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 34 of file RunGui\&.cpp\&.
.SS "void RunGui::handleHelpBntSlot ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 40 of file RunGui\&.cpp\&.
.SS "void RunGui::handleNextBtnSlot ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 28 of file RunGui\&.cpp\&.
.SS "void RunGui::initBtns ()"

.PP
Definition at line 52 of file RunGui\&.cpp\&.
.SS "void RunGui::loadPage_1 ()"

.PP
Definition at line 149 of file RunGui\&.cpp\&.
.SS "void RunGui::loadPage_2 ()"

.PP
Definition at line 165 of file RunGui\&.cpp\&.
.SS "void RunGui::loadPage_3 ()"

.PP
Definition at line 181 of file RunGui\&.cpp\&.
.SS "void RunGui::reset ()"

.PP
Definition at line 80 of file RunGui\&.cpp\&.
.SS "void RunGui::swapBackPage ()"

.PP
Definition at line 89 of file RunGui\&.cpp\&.
.SS "void RunGui::swapNextPage ()"

.PP
Definition at line 113 of file RunGui\&.cpp\&.
.SS "QString * RunGui::toString ()"

.PP
Definition at line 197 of file RunGui\&.cpp\&.
.SS "void RunGui::unloadPage_1 ()"

.PP
Definition at line 157 of file RunGui\&.cpp\&.
.SS "void RunGui::unloadPage_2 ()"

.PP
Definition at line 173 of file RunGui\&.cpp\&.
.SS "void RunGui::unloadPage_3 ()"

.PP
Definition at line 189 of file RunGui\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QPushButton* RunGui::backBtn\fC [private]\fP"

.PP
Definition at line 40 of file RunGui\&.h\&.
.SS "QHBoxLayout* RunGui::buttonLayout\fC [private]\fP"

.PP
Definition at line 47 of file RunGui\&.h\&.
.SS "QPushButton* RunGui::cancelBtn\fC [private]\fP"

.PP
Definition at line 44 of file RunGui\&.h\&.
.SS "\fBPage\fP RunGui::currentPage\fC [private]\fP"

.PP
Definition at line 38 of file RunGui\&.h\&.
.SS "QPushButton* RunGui::finishBtn\fC [private]\fP"

.PP
Definition at line 42 of file RunGui\&.h\&.
.SS "QPushButton* RunGui::helpBtn\fC [private]\fP"

.PP
Definition at line 43 of file RunGui\&.h\&.
.SS "QPushButton* RunGui::nextBtn\fC [private]\fP"

.PP
Definition at line 41 of file RunGui\&.h\&.
.SS "QGridLayout* RunGui::outerLayoutPtr\fC [private]\fP"

.PP
Definition at line 46 of file RunGui\&.h\&.
.SS "\fBRunPage_1\fP* RunGui::runPage_1Ptr\fC [private]\fP"

.PP
Definition at line 49 of file RunGui\&.h\&.
.SS "\fBRunPage_2\fP* RunGui::runPage_2Ptr\fC [private]\fP"

.PP
Definition at line 50 of file RunGui\&.h\&.
.SS "\fBRunPage_3\fP* RunGui::runPage_3Ptr\fC [private]\fP"

.PP
Definition at line 51 of file RunGui\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
