.TH "/home/james/NetBeansProjects/ride/src/RunPage_1.h" 3 "Tue Jun 2 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/RunPage_1.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QLineEdit>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include <QButtonGroup>\fP
.br
\fC#include <QRadioButton>\fP
.br
\fC#include <QGridLayout>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRunPage_1\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
