.TH "/home/james/NetBeansProjects/ride/src/RunPage_2.cpp" 3 "Sat Jun 6 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/RunPage_2.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'RunPage_2\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
