.TH "RunPage_2" 3 "Tue Jun 2 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RunPage_2 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RunPage_2\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRunPage_2\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetLaunchFileStrPtr\fP ()"
.br
.ti -1c
.RI "QString * \fBgetLaunchFileStrPtr\fP ()"
.br
.ti -1c
.RI "\fB~RunPage_2\fP ()"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "void \fBhandleSelectLaunchFilePbPtrSlot\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QLineEdit * \fBlaunchFileLePtr\fP"
.br
.ti -1c
.RI "QFileDialog * \fBlaunchFileDialogPtr\fP"
.br
.ti -1c
.RI "QPushButton * \fBselectLaunchFilePbPtr\fP"
.br
.ti -1c
.RI "QGridLayout * \fBouterLayoutPtr\fP"
.br
.ti -1c
.RI "QString * \fBlaunchFileStrPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file RunPage_2\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RunPage_2::RunPage_2 (QWidget *parent = \fC0\fP)"

.PP
Definition at line 4 of file RunPage_2\&.cpp\&.
.SS "RunPage_2::~RunPage_2 ()"

.PP
Definition at line 39 of file RunPage_2\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QString * RunPage_2::getLaunchFileStrPtr ()"

.PP
Definition at line 33 of file RunPage_2\&.cpp\&.
.SS "void RunPage_2::handleSelectLaunchFilePbPtrSlot ()\fC [private]\fP, \fC [slot]\fP"

.PP
Definition at line 20 of file RunPage_2\&.cpp\&.
.SS "void RunPage_2::setLaunchFileStrPtr ()"

.PP
Definition at line 27 of file RunPage_2\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QFileDialog* RunPage_2::launchFileDialogPtr\fC [private]\fP"

.PP
Definition at line 23 of file RunPage_2\&.h\&.
.SS "QLineEdit* RunPage_2::launchFileLePtr\fC [private]\fP"

.PP
Definition at line 22 of file RunPage_2\&.h\&.
.SS "QString* RunPage_2::launchFileStrPtr\fC [private]\fP"

.PP
Definition at line 28 of file RunPage_2\&.h\&.
.SS "QGridLayout* RunPage_2::outerLayoutPtr\fC [private]\fP"

.PP
Definition at line 26 of file RunPage_2\&.h\&.
.SS "QPushButton* RunPage_2::selectLaunchFilePbPtr\fC [private]\fP"

.PP
Definition at line 24 of file RunPage_2\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
