.TH "/home/james/NetBeansProjects/ride/src/SaveAll.h" 3 "Sat Jun 6 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/SaveAll.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QDir>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QTextEdit>\fP
.br
\fC#include <QPlainTextEdit>\fP
.br
\fC#include <QTextStream>\fP
.br
\fC#include <QVector>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'RideFile\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBSaveAll\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSaveAll::pushToRideFilePtrVec\fP (\fBRideFile\fP *rideFilePtr)"
.br
.ti -1c
.RI "void \fBSaveAll::removeFromRideFileVec\fP (\fBRideFile\fP *rideFilePtr)"
.br
.ti -1c
.RI "QVector< \fBRideFile\fP * > \fBSaveAll::getRideFilePtrVec\fP ()"
.br
.ti -1c
.RI "void \fBSaveAll::save\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "QVector< \fBRideFile\fP * > \fBSaveAll::rideFilePtrVec\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
