.TH "SaveAll" 3 "Tue Jun 2 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SaveAll \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBpushToRideFilePtrVec\fP (\fBRideFile\fP *rideFilePtr)"
.br
.ti -1c
.RI "void \fBremoveFromRideFileVec\fP (\fBRideFile\fP *rideFilePtr)"
.br
.ti -1c
.RI "QVector< \fBRideFile\fP * > \fBgetRideFilePtrVec\fP ()"
.br
.ti -1c
.RI "void \fBsave\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "QVector< \fBRideFile\fP * > \fBrideFilePtrVec\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QVector< \fBRideFile\fP * > SaveAll::getRideFilePtrVec ()"

.PP
Definition at line 28 of file SaveAll\&.cpp\&.
.SS "void SaveAll::pushToRideFilePtrVec (\fBRideFile\fP *rideFilePtr)"

.PP
Definition at line 7 of file SaveAll\&.cpp\&.
.SS "void SaveAll::removeFromRideFileVec (\fBRideFile\fP *rideFilePtr)"

.PP
Definition at line 13 of file SaveAll\&.cpp\&.
.SS "void SaveAll::save ()"

.PP
Definition at line 34 of file SaveAll\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "QVector< \fBRideFile\fP * > SaveAll::rideFilePtrVec"

.PP
Definition at line 4 of file SaveAll\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
