.TH "ScoutVarDat" 3 "Sat Jun 6 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScoutVarDat \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ScoutVarDat\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScoutVarDat\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetVarNmStrPtr\fP (QString *\fBvarNmStrPtr\fP)"
.br
.ti -1c
.RI "QString * \fBgetVarNmStrPtr\fP ()"
.br
.ti -1c
.RI "void \fBsetVarTypeStrPtr\fP (QString *\fBvarTypeStrPtr\fP)"
.br
.ti -1c
.RI "QString * \fBgetVarTypeStrPtr\fP ()"
.br
.ti -1c
.RI "QString * \fBtoString\fP ()"
.br
.ti -1c
.RI "\fB~ScoutVarDat\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QString * \fBvarNmStrPtr\fP"
.br
.ti -1c
.RI "QString * \fBvarTypeStrPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file ScoutVarDat\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ScoutVarDat::ScoutVarDat (QWidget *parent = \fC0\fP)"

.PP
Definition at line 4 of file ScoutVarDat\&.cpp\&.
.SS "ScoutVarDat::~ScoutVarDat ()"

.PP
Definition at line 45 of file ScoutVarDat\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QString * ScoutVarDat::getVarNmStrPtr ()"

.PP
Definition at line 17 of file ScoutVarDat\&.cpp\&.
.SS "QString * ScoutVarDat::getVarTypeStrPtr ()"

.PP
Definition at line 29 of file ScoutVarDat\&.cpp\&.
.SS "void ScoutVarDat::setVarNmStrPtr (QString *varNmStrPtr)"

.PP
Definition at line 11 of file ScoutVarDat\&.cpp\&.
.SS "void ScoutVarDat::setVarTypeStrPtr (QString *varTypeStrPtr)"

.PP
Definition at line 23 of file ScoutVarDat\&.cpp\&.
.SS "QString * ScoutVarDat::toString ()"

.PP
Definition at line 35 of file ScoutVarDat\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QString* ScoutVarDat::varNmStrPtr\fC [private]\fP"

.PP
Definition at line 19 of file ScoutVarDat\&.h\&.
.SS "QString* ScoutVarDat::varTypeStrPtr\fC [private]\fP"

.PP
Definition at line 20 of file ScoutVarDat\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
