.TH "ScoutData" 3 "Fri Jun 12 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScoutData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ScoutData\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScoutData\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBload\fP ()"
.br
.ti -1c
.RI "void \fBrefresh\fP ()"
.br
.ti -1c
.RI "QString * \fBtoString\fP ()"
.br
.ti -1c
.RI "\fB~ScoutData\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QStringList * \fBloadedFilesStrLstPtr\fP"
.br
.ti -1c
.RI "QVector< \fBScoutFileDat\fP * > * \fBscoutLibDatPtrVecPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file ScoutData\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ScoutData::ScoutData (QWidget *parent = \fC0\fP)"

.PP
Definition at line 4 of file ScoutData\&.cpp\&.
.SS "ScoutData::~ScoutData ()"

.PP
Definition at line 36 of file ScoutData\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void ScoutData::load ()"

.PP
Definition at line 11 of file ScoutData\&.cpp\&.
.SS "void ScoutData::refresh ()"

.PP
Definition at line 17 of file ScoutData\&.cpp\&.
.SS "QString * ScoutData::toString ()"

.PP
Definition at line 23 of file ScoutData\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QStringList* ScoutData::loadedFilesStrLstPtr\fC [private]\fP"

.PP
Definition at line 25 of file ScoutData\&.h\&.
.SS "QVector<\fBScoutFileDat\fP*>* ScoutData::scoutLibDatPtrVecPtr\fC [private]\fP"

.PP
Definition at line 26 of file ScoutData\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
