.TH "/home/james/NetBeansProjects/ride/src/ScoutData.h" 3 "Sat Jun 6 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/ScoutData.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QDir>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QStringList>\fP
.br
\fC#include <QVector>\fP
.br
\fC#include 'ScoutFileDat\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBScoutData\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
