.TH "SearchWidget" 3 "Fri Jun 12 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SearchWidget \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SearchWidget\&.h>\fP
.PP
Inherits QLineEdit\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSearchWidget\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "void \fBsetSearchInputStrPtr\fP ()"
.br
.ti -1c
.RI "QString * \fBgetSearchInputStrPtr\fP ()"
.br
.ti -1c
.RI "\fB~SearchWidget\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QString * \fBsearchInputStrPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file SearchWidget\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SearchWidget::SearchWidget (QWidget *parent = \fC0\fP)"

.PP
Definition at line 4 of file SearchWidget\&.cpp\&.
.SS "SearchWidget::~SearchWidget ()"

.PP
Definition at line 22 of file SearchWidget\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "QString * SearchWidget::getSearchInputStrPtr ()"

.PP
Definition at line 16 of file SearchWidget\&.cpp\&.
.SS "void SearchWidget::setSearchInputStrPtr ()"

.PP
Definition at line 10 of file SearchWidget\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QString* SearchWidget::searchInputStrPtr\fC [private]\fP"

.PP
Definition at line 26 of file SearchWidget\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
