.TH "SplashScreen" 3 "Fri Jun 12 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SplashScreen \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SplashScreen\&.h>\fP
.PP
Inherits QSplashScreen\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSplashScreen\fP ()"
.br
.ti -1c
.RI "\fB~SplashScreen\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QPixmap * \fBlogoPixmapPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file SplashScreen\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SplashScreen::SplashScreen ()"

.PP
Definition at line 4 of file SplashScreen\&.cpp\&.
.SS "SplashScreen::~SplashScreen ()"

.PP
Definition at line 14 of file SplashScreen\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "QPixmap* SplashScreen::logoPixmapPtr\fC [private]\fP"

.PP
Definition at line 18 of file SplashScreen\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
