.TH "Terminal" 3 "Tue Jun 2 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Terminal \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Terminal\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "int \fBstart\fP ()"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "void \fBexited\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTerminal\fP (QWidget *=0)"
.br
.ti -1c
.RI "\fB~Terminal\fP ()"
.br
.ti -1c
.RI "int \fBisRunning\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBcols\fP"
.br
.ti -1c
.RI "int \fBrows\fP"
.br
.ti -1c
.RI "QProcess * \fBtermProcess\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file Terminal\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Terminal::Terminal (QWidget *parent = \fC0\fP)"

.PP
Definition at line 4 of file Terminal\&.cpp\&.
.SS "Terminal::~Terminal ()"

.PP
Definition at line 65 of file Terminal\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Terminal::exited ()\fC [signal]\fP"

.SS "int Terminal::isRunning ()"

.PP
Definition at line 11 of file Terminal\&.cpp\&.
.SS "int Terminal::start ()\fC [slot]\fP"

.PP
Definition at line 17 of file Terminal\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int Terminal::cols\fC [private]\fP"

.PP
Definition at line 35 of file Terminal\&.h\&.
.SS "int Terminal::rows\fC [private]\fP"

.PP
Definition at line 35 of file Terminal\&.h\&.
.SS "QProcess* Terminal::termProcess\fC [private]\fP"

.PP
Definition at line 36 of file Terminal\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
