.TH "/home/james/NetBeansProjects/ride/src/Terminal.h" 3 "Sat Jun 6 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/Terminal.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QProcess>\fP
.br
\fC#include <QtGui>\fP
.br
\fC#include <X11/Xlib\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTerminal\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBXTERM_CMD\fP   '/usr/bin/xterm'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define XTERM_CMD   '/usr/bin/xterm'"

.PP
Definition at line 10 of file Terminal\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
