.TH "/home/james/NetBeansProjects/ride/src/TreeItemIconInit.h" 3 "Sat Jun 6 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/TreeItemIconInit.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QTreeWidgetItem>\fP
.br
\fC#include <QIcon>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBTreeItemIconInit\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBTreeItemIconInit::setIcon\fP (QTreeWidgetItem *child)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
