.TH "/home/james/NetBeansProjects/ride/src/UnixConsoleText.h" 3 "Tue Jun 2 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/UnixConsoleText.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBUnixConsoleText\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "string * \fBUnixConsoleText::red\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::green\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::yellow\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::blue\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::purple\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::cyan\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::gray\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::boldRed\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::boldGreen\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::boldYellow\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::boldBlue\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::boldPurple\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::boldCyan\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::boldGray\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::italicRed\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::italicGreen\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::italicYellow\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::italicBlue\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::italicPurple\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::italicCyan\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::italicGray\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::underlinedRed\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::underlinedGreen\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::underlinedYellow\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::underlinedBlue\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::underlinedPurple\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::underlinedCyan\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBUnixConsoleText::underlinedGray\fP (string *textStrPtr)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
