.TH "/home/james/NetBeansProjects/ride/src/WindowsConsoleText.h" 3 "Tue Jun 2 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/WindowsConsoleText.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBWindowsConsoleText\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "string * \fBWindowsConsoleText::red\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::green\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::yellow\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::blue\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::purple\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::cyan\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::gray\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::boldRed\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::boldGreen\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::boldYellow\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::boldBlue\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::boldPurple\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::boldCyan\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::boldGray\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::italicRed\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::italicGreen\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::italicYellow\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::italicBlue\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::italicPurple\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::italicCyan\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::italicGray\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::underlinedRed\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::underlinedGreen\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::underlinedYellow\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::underlinedBlue\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::underlinedPurple\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::underlinedCyan\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBWindowsConsoleText::underlinedGray\fP (string *textStrPtr)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
