.TH "/home/james/NetBeansProjects/ride/src/WindowsConsoleText.cpp" 3 "Tue Jun 2 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/WindowsConsoleText.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'WindowsConsoleText\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "string * \fBred\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBgreen\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fByellow\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBblue\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBpurple\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBcyan\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBgray\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBboldRed\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBboldGreen\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBboldYellow\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBboldBlue\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBboldPurple\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBboldCyan\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBboldGray\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBitalicRed\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBitalicGreen\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBitalicYellow\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBitalicBlue\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBitalicPurple\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBitalicCyan\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBitalicGray\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBunderlinedRed\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBunderlinedGreen\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBunderlinedYellow\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBunderlinedBlue\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBunderlinedPurple\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBunderlinedCyan\fP (string *textStrPtr)"
.br
.ti -1c
.RI "string * \fBunderlinedGray\fP (string *textStrPtr)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "string* blue (string *textStrPtr)"
Method to return blue textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed blue\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Blue textStrPtr\&. 
.RE
.PP

.PP
Definition at line 22 of file WindowsConsoleText\&.cpp\&.
.SS "string* boldBlue (string *textStrPtr)"
Method to return bold blue textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed bold blue\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Bold blue textStrPtr\&. 
.RE
.PP

.PP
Definition at line 67 of file WindowsConsoleText\&.cpp\&.
.SS "string* boldCyan (string *textStrPtr)"
Method to return bold cyan textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed bold cyan\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Bold cyan textStrPtr\&. 
.RE
.PP

.PP
Definition at line 79 of file WindowsConsoleText\&.cpp\&.
.SS "string* boldGray (string *textStrPtr)"
Method to return bold gray textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed bold gray\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Bold gray textStrPtr\&. 
.RE
.PP

.PP
Definition at line 85 of file WindowsConsoleText\&.cpp\&.
.SS "string* boldGreen (string *textStrPtr)"
Method to return bold green textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed bold green\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Bold green textStrPtr\&. 
.RE
.PP

.PP
Definition at line 55 of file WindowsConsoleText\&.cpp\&.
.SS "string* boldPurple (string *textStrPtr)"
Method to return bold purple textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed bold purple\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Bold purple textStrPtr\&. 
.RE
.PP

.PP
Definition at line 73 of file WindowsConsoleText\&.cpp\&.
.SS "string* boldRed (string *textStrPtr)"
Method to return bold red textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed bold red\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Bold red textStrPtr\&. 
.RE
.PP

.PP
Definition at line 49 of file WindowsConsoleText\&.cpp\&.
.SS "string* boldYellow (string *textStrPtr)"
Method to return bold yellow textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed bold yellow\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Bold yellow textStrPtr\&. 
.RE
.PP

.PP
Definition at line 61 of file WindowsConsoleText\&.cpp\&.
.SS "string* cyan (string *textStrPtr)"
Method to return cyan textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed cyan\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Cyan textStrPtr\&. 
.RE
.PP

.PP
Definition at line 34 of file WindowsConsoleText\&.cpp\&.
.SS "string* gray (string *textStrPtr)"
Method to return gray textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed gray\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Gray textStrPtr\&. 
.RE
.PP

.PP
Definition at line 40 of file WindowsConsoleText\&.cpp\&.
.SS "string* green (string *textStrPtr)"
Method to return green textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed green\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Green textStrPtr\&. 
.RE
.PP

.PP
Definition at line 10 of file WindowsConsoleText\&.cpp\&.
.SS "string* italicBlue (string *textStrPtr)"
Method to return italic blue textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed italic blue\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Italic blue textStrPtr\&. 
.RE
.PP

.PP
Definition at line 112 of file WindowsConsoleText\&.cpp\&.
.SS "string* italicCyan (string *textStrPtr)"
Method to return italic cyan textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed italic cyan\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Italic cyan textStrPtr\&. 
.RE
.PP

.PP
Definition at line 124 of file WindowsConsoleText\&.cpp\&.
.SS "string* italicGray (string *textStrPtr)"
Method to return italic gray textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed italic gray\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Italic gray textStrPtr\&. 
.RE
.PP

.PP
Definition at line 130 of file WindowsConsoleText\&.cpp\&.
.SS "string* italicGreen (string *textStrPtr)"
Method to return italic green textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed italic green\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Italic green textStrPtr\&. 
.RE
.PP

.PP
Definition at line 100 of file WindowsConsoleText\&.cpp\&.
.SS "string* italicPurple (string *textStrPtr)"
Method to return italic purple textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed italic purple\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Italic purple textStrPtr\&. 
.RE
.PP

.PP
Definition at line 118 of file WindowsConsoleText\&.cpp\&.
.SS "string* italicRed (string *textStrPtr)"
Method to return italic red textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed italic red\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Italic red textStrPtr\&. 
.RE
.PP

.PP
Definition at line 94 of file WindowsConsoleText\&.cpp\&.
.SS "string* italicYellow (string *textStrPtr)"
Method to return italic yellow textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed italic yellow\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Italic yellow textStrPtr\&. 
.RE
.PP

.PP
Definition at line 106 of file WindowsConsoleText\&.cpp\&.
.SS "string* purple (string *textStrPtr)"
Method to return purple textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed purple\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Purple textStrPtr\&. 
.RE
.PP

.PP
Definition at line 28 of file WindowsConsoleText\&.cpp\&.
.SS "string* red (string *textStrPtr)"
Method to return red textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed red\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Red textStrPtr\&. 
.RE
.PP

.PP
Definition at line 4 of file WindowsConsoleText\&.cpp\&.
.SS "string* underlinedBlue (string *textStrPtr)"
Method to return underlined blue textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed underlined blue\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Underlined blue textStrPtr\&. 
.RE
.PP

.PP
Definition at line 157 of file WindowsConsoleText\&.cpp\&.
.SS "string* underlinedCyan (string *textStrPtr)"
Method to return underlined cyan textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed underlined cyan\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Underlined cyan textStrPtr\&. 
.RE
.PP

.PP
Definition at line 169 of file WindowsConsoleText\&.cpp\&.
.SS "string* underlinedGray (string *textStrPtr)"
Method to return underlined gray textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed underlined gray\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Underlined gray textStrPtr\&. 
.RE
.PP

.PP
Definition at line 175 of file WindowsConsoleText\&.cpp\&.
.SS "string* underlinedGreen (string *textStrPtr)"
Method to return underlined green textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed underlined green\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Underlined green textStrPtr\&. 
.RE
.PP

.PP
Definition at line 145 of file WindowsConsoleText\&.cpp\&.
.SS "string* underlinedPurple (string *textStrPtr)"
Method to return underlined purple textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed underlined purple\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Underlined purple textStrPtr\&. 
.RE
.PP

.PP
Definition at line 163 of file WindowsConsoleText\&.cpp\&.
.SS "string* underlinedRed (string *textStrPtr)"
Method to return underlined red textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed underlined red\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Underlined red textStrPtr\&. 
.RE
.PP

.PP
Definition at line 139 of file WindowsConsoleText\&.cpp\&.
.SS "string* underlinedYellow (string *textStrPtr)"
Method to return underlined yellow textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed underlined yellow\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Underlined yellow textStrPtr\&. 
.RE
.PP

.PP
Definition at line 151 of file WindowsConsoleText\&.cpp\&.
.SS "string* yellow (string *textStrPtr)"
Method to return yellow textStrPtr\&.
.PP
\fBParameters:\fP
.RS 4
\fItextStrPtr\fP textStrPtr to be printed yellow\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Yellow textStrPtr\&. 
.RE
.PP

.PP
Definition at line 16 of file WindowsConsoleText\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
