.TH "/home/james/NetBeansProjects/ride/src/XmlMaster.h" 3 "Sat Jun 6 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/james/NetBeansProjects/ride/src/XmlMaster.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QtXml>\fP
.br
\fC#include <QDomElement>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBXmlMaster\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBXmlMaster::loadFile\fP (QFile *filePtr)"
.br
.ti -1c
.RI "void \fBXmlMaster::printXmlFile\fP (QFile *filePtr)"
.br
.ti -1c
.RI "void \fBXmlMaster::insertAfterLastOccurrence\fP (QFile *filePtr, QString *occurrenceOfStrPtr, QString *insertionStrPtr)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "QFile * \fBXmlMaster::filePtr\fP"
.br
.ti -1c
.RI "QDomDocument * \fBXmlMaster::xmlDomDocPtr\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
