.TH "XmlMaster" 3 "Fri Jun 12 2015" "Version 0.0.1" "RIDE" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XmlMaster \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBloadFile\fP (QFile *\fBfilePtr\fP)"
.br
.ti -1c
.RI "void \fBprintXmlFile\fP (QFile *\fBfilePtr\fP)"
.br
.ti -1c
.RI "void \fBinsertAfterLastOccurrence\fP (QFile *\fBfilePtr\fP, QString *occurrenceOfStrPtr, QString *insertionStrPtr)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "QFile * \fBfilePtr\fP"
.br
.ti -1c
.RI "QDomDocument * \fBxmlDomDocPtr\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void XmlMaster::insertAfterLastOccurrence (QFile *filePtr, QString *occurrenceOfStrPtr, QString *insertionStrPtr)"

.PP
Definition at line 27 of file XmlMaster\&.cpp\&.
.SS "void XmlMaster::loadFile (QFile *filePtr)"

.PP
Definition at line 4 of file XmlMaster\&.cpp\&.
.SS "void XmlMaster::printXmlFile (QFile *filePtr)"

.PP
Definition at line 21 of file XmlMaster\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "QFile* XmlMaster::filePtr"

.PP
Definition at line 23 of file XmlMaster\&.h\&.
.SS "QDomDocument* XmlMaster::xmlDomDocPtr"

.PP
Definition at line 24 of file XmlMaster\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for RIDE from the source code\&.
